### ISSUE TITLE
Creacion de usuarios

### ISSUE THREAD

**Issue by nfuerte** [Desarrollo-CeSPI/kimkelen#125]
Hola!

Estoy trabajando con la version 2.18.0 en Windows. 
Cuando creo o edito un usuario no aparecen las opciones para seleccionar los diferentes grupos de usuarios. Los registros si están en la base de datos.

Saludos!

**Comment by chrodriguez** [comment]
Trabajás con el usuario admin?

**Comment by nfuerte** [comment]
Si, estoy trabajando con el usuario admin.
Ahora he actualizado a 2.18.4.
Tengo un usuario que lo asocié a 2 grupos (Preceptor y oficina de alumnos) y no puedo editarlo (estoy suponiendo q el Admin tiene permisos para editar y eliminar a todos los usuarios).
Además he creado otro usuario pero la única opción q aparece es asociarlo al grupo Admin.
Leí el manual y no he encontrdo nada tan específico la respecto.
Gracias!!!!

**Comment by nfuerte** [comment]
¿Alguna sugerencia la respecto?
Gracias!

**Comment by ecorrons** [comment]
Hola @nfuerte ! Los preceptores y docentes se manejan desde el menú Académica->Personal del colegio->Preceptores, por ejemplo
