### ISSUE TITLE
Nueva instalación

### ISSUE THREAD

**Issue by nfuerte** [Desarrollo-CeSPI/kimkelen#127]
Hola!
He instalado Kimkelen sobre windows sin problemas.
En esta ocasión lo hago sobre un servidor remoto con Debian, proxy reverso y uso una maquina virtual con windows.
No he tenido problemas al instalar pero al intentar ingresar al sistema muestra el siguiente error (luego de cargar datos de login): 
   The proxy server received an invalid response from an upstream server.
   The proxy server could not handle the request POST /kimkelen-2.18.0/web/login.
He tratado de resolverlo pero no encuentro la causa del mismo. Tampoco sé si es referido a alguna configuración particular que deba tener en cuenta en estas condiciones.

¿Alguna sugerencia al respecto?
Gracias!

**Comment by chrodriguez** [comment]
Se han solucionado los problemas planteados? El problema que mencionás sobre: 
```
The proxy server received an invalid response from an upstream server.
```
Parece más bien un problema de configuración del entorno que de kimkelen. En nuestros servidores tenemos una arquitectura similar y no tenemos problemas

**Comment by chrodriguez** [comment]
Aprovecho para comentarles que hemos desarrollado un contenedor docker que simplifica la instalación de kimkelen: https://hub.docker.com/r/cespi/kimkelen/
