### ISSUE TITLE
Error 500 al querer exportar boletín

### ISSUE THREAD

**Issue by gcesario** [Desarrollo-CeSPI/kimkelen#143]
He instalado kimkelen en un servidor Centos con php 5.3.27.  Al hacer clic en imprimir boletín lo previsualizo correctamente pero luego al hacer clic en "exportar boletín" recibo un mensaje indicando error 500.

Podrían ayudarnos, muchas gracias y saludos

Gustavo

**Comment by chrodriguez** [comment]
Cómo han instalado el wkhtmltopdf? Porque el que viene por defecto en algunas distribuciones no funciona de forma adecuada. Instalen el que indica la página principal del proyecto:

http://wkhtmltopdf.org/downloads.html

**Comment by gcesario** [comment]
Cristian muchas gracias por tu respuesta. Te cuento que se trata fe un Centos 6.

Tenemos instalado el complemento y lo instalamos de acuerdo a las instrucciones de github
Instalar [wkhtmltopdf](http://code.google.com/p/wkhtmltopdf/). Debe estar
    instalado en /usr/bin/wkhtmltopdf o especificarse la ruta en el archivo
    apps/frontend/config/app.yml
    Ejemplo de instalación:

    (para ubuntu 32bits OS)
    wget http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9-static-i386.tar.bz2
    tar xvjf wkhtmltopdf-0.9.9-static-i386.tar.bz2
    mv wkhtmltopdf-i386 /usr/local/bin/wkhtmltopdf
    chmod +x /usr/local/bin/wkhtmltopdf

Sigue el mismo error

Genera un pdf de 0 kb

**Comment by chrodriguez** [comment]
Podras subir los logs de apache error log. Es más, si podés, probá la aplicación en modo dev para verificar si aparecen más errores

**Comment by gcesario** [comment]
En modo dev no se produce ningún error. Hacemos clic en exportar a pdf y muestra un pdf en blanco de 0kb.

La versión que tenemos instalada es la del tutorial http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9-static-i386.tar.bz2  Es correcta?

**Comment by chrodriguez** [comment]
Y en los logs no aparece nada?

 Por las dudas proba wkhtmltopdf con la url de google verificando si funciona

**Comment by gcesario** [comment]
Christian, cómo estás?

Pudimos solucionar el problema! Desinstalamos la versión de wkhtmltopdf e instalamos una especialmente diseñada para centos 6.

Muchísimas gracias por su ayuda.

**Comment by RizerJoaquin** [comment]
El mismo problema... el wkhtmltopdf funciona correctamente en el servidor y se le crearon softlinks en /usr/bin (desde /usr/local/bin) pero genera unicamente un pdf con 0 bytes.
Por otro lado no existe ningun archivo en el path: apps/frontend/config/app.yml en el proyecto donde pueda cambiar el path del binario.
Alguna otra cosa a tener en cuenta?

**Comment by chrodriguez** [comment]
Como instalaste el paquete de wkhtmltopdf?

**Comment by RizerJoaquin** [comment]
Son 2 servidores prueba y producción... prueba con centos 7 ya quedó andando mediante un wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos7-amd64.rpm y luego instalándolo (rpm -Uvh wkhtml...).
Pero en el servidor de producción con un centos 6.7 el kimkelen sigue sin encontrar el binario: se instaló haciendo un wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm y luego rpm -Uvh wkhtml...
Se verificó que se instala correctamente en /user/local/bin y funciona nbien luego se le asignó permisos chmod -R 0777 a esos archivos... Pero kimkelen sigue sin reconocerlo :S (throw new LogicException("The executable ({$this->getExecutable()}) does not exist. Please install wkhtmltopdf.");)
Que se me está escapando? :S

**Comment by ncuesta** [comment]
Estas seguro que lo esta buscando en donde esta instalado?

Si no está en esa ubicación, podes hacer un link simbólico al binario ubicado
donde lo trate de encontrar o configurar el path correcto en el app.yml que
mencionaste antes (creándolo si no existe aún).

-----
CeSPI 
Centro Superior para el Procesamiento de la Informaci�n

Universidad Nacional de La Plata
-------------------------------------------------------------------------------
Proteja el Medioambiente. No imprima este mail si no es absolutamente necesario

**Comment by RizerJoaquin** [comment]
kimkelen dice: The executable (/usr/local/bin/wkhtmltopdf) does not exist. Please install wkhtmltopdf.
Pero claro que está instalado en ese directorio! Por lo que no hay ningún ln que hacer... :S
Cambié permisos de los archivos y hasta resetié apache... Estoy x meterme a toquetear el archivo: pm_pdf_kit.yml pero wkhtmltopdf está instalado en el lugar x default (/usr/local/bin/wkhtmltopdf) por lo que debería andar :S
 ya se me están acabando las ideas.

**Comment by chrodriguez** [comment]
Sinceramente, en todas las instalaciones que tenemos disponibles nos funciona. Pudiste solucionarlo? Por el momento cerramos el ticket, cualquier novedad, creá nuevamente un ticket con el problema.

Gracias!
