### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by ojedavd** [Desarrollo-CeSPI/kimkelen#144]
Tengo el mod_rewrite habilitado. Corri todos estos comandos 

php symfony kimkelen:flavor demo

php symfony propel:build-model
php symfony propel:build-forms
php symfony propel:build-filters
php symfony propel:build-sql
php symfony propel:insert-sql

php symfony plugin:publish
php symfony project:permissions

sin obtener ningun error.

Llegue a la pantalla de login, pero cuando me logueo obtengo el siguiente mensaje:

The requested URL /kimkelen/web/login was not found on this server.

**Comment by chrodriguez** [comment]
Si tenes el mod rewrite habilitado y te da ese error es porque no está leyendo el .htaccess de symfony. Para que lo lea tenes que además tener allow override all

**Comment by ojedavd** [comment]
mi error era el siguiente. en el archivo
/etc/default/sites-availables/default tenia los allow override en none.
muchas gracias Christian.

Saludos

2015-01-13 0:03 GMT-03:00 Christian Rodriguez <notifications@github.com>:
