### ISSUE TITLE
Error 500 al querer exportar alumnos

### ISSUE THREAD

**Issue by gcesario** [Desarrollo-CeSPI/kimkelen#145]
Estimados recibo el siguiente error:

Fatal error: Call to a member function getId() on a non-object in /home/gcsistemas/domains/gc-sistemas.com.ar/public_html/demo/kimkelen/lib/model/Student.php on line 976

Al tratar de exportar alumnos : Alumnos --> Exportar --> selecciono todos los campos.

Muchas gracias y saludos

**Comment by ecorrons** [comment]
Hola gcesario, el problema se debía a que al poner Exportar y seleccionar todos los campos, entre ellos figura 'Materias desaprobadas'. Como debés estar probando con una base de datos que solo tiene un año lectivo y no hay previo, cuando el sistema intenta buscar años lectivos previos se rompía. Era un error de código. 
Si te actualizás el código ya debería estar arreglado. Sin embargo, no está hecho un nuevo *tag* con este cambio. Si no querés actualizar por ahora el código en tu server probá la acción exportar deseleccionando el campo de 'Materias que desaprobó', ya que aún no las hay.

Saludos

**Comment by gcesario** [comment]
Muchas gracias!
