### ISSUE TITLE
Mailing a Tutores

### ISSUE THREAD

**Issue by gcesario** [Desarrollo-CeSPI/kimkelen#148]
Estimados, me parecería interesante agregar la siguiente funcionalidad al sistema:

En alumnos --> listado de tutores aparece una pantalla para filtrar los tutores, incluso por división.  Me parecería muy util agregar la posibilidad de escribir un mensaje y enviárselo en forma masiva a los tutores que se filtraron en esta pantalla.

Qué les parece?  Sería muy útil para realizar comunicados a todos los tutores de una división por ejemplo.

Espero sus comentarios, muchas gracias y saludos

Gustavo

**Comment by chrodriguez** [comment]
Hola Gustavo, lo consideraremos como una mejora. Gracias por la propuesta!
