### ISSUE TITLE
Consulta sobre estructura de base de datos

### ISSUE THREAD

**Issue by esavoy** [Desarrollo-CeSPI/kimkelen#152]
Hola, quería consultar cual es el modelo de datos que tengo que crear para que funcione el sistema. Sigo los pasos que están en la documentación (https://github.com/Desarrollo-CeSPI/kimkelen) pero cuando ejecuto el comando "php symfony propel:insert-sql" me sale "error la tabla personal no existe", esto es lógico ya que lo único que hice yo fue crear la bd manualmente pero sin ninguna tabla, la estructura esta vacía, porque no conozco el modelo. 
Podrían por favor informarme como puedo seguir con la instalación?
MUCHAS GRACIAS

**Comment by chrodriguez** [comment]
Probaste con correr symfony propel:build-all-load ?
