### ISSUE TITLE
Problema en Instalación kimkelem o demo online 

### ISSUE THREAD

**Issue by fedecoraglio** [Desarrollo-CeSPI/kimkelen#154]
Buenas, hace unos días que un colegio del interior de Córdoba esta interesado en empezar a informatizar sus actividades y me consultaron ami para ver que se podia realizar. Googleando y buscando software de código abierto me encontre con kinkelen. Mi idea es mostrarle este sistema y ver si se puede ir implementando con mi ayuda y personal del instituto. 

Estoy tratando de instalarlo usando una maquina virtual en mi compu y no he podido. El mayor problema que encuentro es que no puedo conseguir la version de PHP mejor a 5.4, que es requerimiento del sistema. Intente lo siguiente:

1) Sistema operativo Xubuntu 14.04 (que es un Ubuntu liviano). Utilizando LAMP puede instalar todo los requerimientos pero con la version de PHP 5.5. Logre que se muestre el login pero cuando intento loguearme me lanza un error 404, estuve viendo el listado de issue y encontre similares a mi problema pero todos recomendaban instalar una version 5.3. Lo pude hacer pero me dejo de funcionar el apache, supongo por cuestiones de librería.

2) Luego intente instalar una version vieja de Ubuntu 12.10 para que utilizando LAMP me instale la version 5.3 de PHP pero me encontre con que la mayoria de los repositories de esta distro ya estan deprecados y no se pueden utilizar. 

3) Volvi a tan querido Windows XP ahi utilizando XAMPP encontre para la version 5.4 de php y me encontre con los problemas de credencias que no podia loguarme debido a que ciertos script de la instalación no se ejecutaron con exito debido justamente a la version de PHP, mas presisamente cuando se ejecutaban script de mysql (existen issue creada sobre este tema que la solución era migrando de version) 

Yo queria consultarle alguna sugerencia con respecto a este inconveniente con la version de PHP. 

Tambien quice utilizar la demo que esta disponible online pero cuando realizo el login me lanza un error 500. 

Mi idea es poder utilizar la aplicación para poder verla y analizar las posibilidades de implementación en un instituto secundario. 

Desde ya muchas gracias y perdon si esto le ocaciono algún inconveniente

**Comment by zcortes** [comment]
Estoy realizando la instalacion sobre windows 7 y tengo el problema en el logeo. Con XP te pasaba igual? En mi caso no carga los datos iniciales (symfony propel:data-load). El error que me arrojaba en un principio se debia al control parental (UAC), para el cual con desactivarlo basta.

**Comment by nfuerte** [comment]
Hola!
Si les sirve, yo lo instale (2.19.3) con windows 7 y Xampp y pude instalar una version más vieja (1.7.7) del mismo con un php 5.3.x y funciona sin problemas. Antes lo tenia con un xampp con un php 5.2.x y tb andaba sin problemas.

**Comment by zcortes** [comment]
Hola!
La version de windows 7 era de 32 o 64 bits? Yo tengo de 64 y lo he intentado con Wamp 2.2e con php 5.3.13 y apache 2.2.22 pero el error que tengo ahora es este: 
*Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
 63 bytes) in C:\wamp\www\kimkelen\lib\symfony\yaml\sfYamlParser.class.php on li
ne 53*

**Comment by nfuerte** [comment]
En la primer instalación tuve un problema similar, que solucione ampliando la memoria en php.ini a 512mb.

**Comment by nfuerte** [comment]
Mi sistema operativo es de 64 bits

**Comment by zcortes** [comment]
Efectivamente cambiando
**memory_limit = 512M**
en el php.ini se soluciona el problema.

**Comment by ncuesta** [comment]
@zcortes Entonces cierro el ticket, si tu instalación fue exitosa. ¡Gracias por usar Kimkëlen!
