### ISSUE TITLE
Problemas en repitentes con previas

### ISSUE THREAD

**Issue by claudiokum** [Desarrollo-CeSPI/kimkelen#159]
Hola, paso a detallar mi inconveniente: tengo un alumno de 1° año que en ciclo 2015 se lleva 3 materias (mas de dos previas repite configurado de esta forma) creo el ciclo 2016 lo matriculo automaticamte y el sistema lo coloca como repitente en 1° año. Vuelve a realizar todas las materias, aprueba todas, cierro el ciclo 2016 creo el nuevo 2017 cuando realizo clic en matricular alumnos del ciclo anterior en el nuevo el sistema me lo mantiene como repitente y no lo pasa a 2° año. Que puedo realizar un cambio en el flavor o que puedo hacer. Me urge tratar de solucionar esto.

**Comment by chrodriguez** [comment]
Lo vamos viendo...

**Comment by claudiokum** [comment]
Hola @chrodriguez : Mil disculpas que te moleste. Es por el tema de los repitientes. Si había alguna posibilidad de agregar en el código de que cuando el alumno repita al siguiente año el sistema no le tome en cuenta las materias del año que repitió para poder pasar al siguiente año. Ejemplo: el alumno de 1º año repite con 3 materias en el siclo 2015. se lo vuelve a inscribir en 1º año en este ciclo 2016, aprueba casi todas se lleva 1. Cuando cierro el siclo 2016 y cambia la vigencia al ciclo 2017 el sistema me lo hace repetir y no lo promueve al 2º año. Me urge debido a que este es el 2º año que utilizo el sistema. Mil disculpas las molestias.

**Comment by palmegonzalez** [comment]
Buenos dias @claudiokum tenes actualizado el sistema al dia de hoy?, estuve chequeando este inconveniente que tenes y no encuentro problema con repitientes que acumulen previas.
