### ISSUE TITLE
Error en actualizacion a 2.18.4

### ISSUE THREAD

**Issue by nfuerte** [Desarrollo-CeSPI/kimkelen#160]
Hola!
He actualizado de 2.18.0 a 2.18.4 y e instalado sin problemas pero da el siguiente error:
Fatal error: Class 'BasepmConfiguration' not found in C:\xampp\htdocs\kimkelen-2.18.4\plugins\pmModuleEnablerPlugin\lib\model\pmConfiguration.php on line 86

Como puedo resolverlo?

Gracias!

**Comment by chrodriguez** [comment]
symfony propel:build-model ??

**Comment by nfuerte** [comment]
Bien! Gracias!
Ejecuté todos los comandos symfony de nuevo y anduvo.
Ahora tengo otro:
500 | Internal Server Error | PropelException
[wrapped: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'student.ORIGIN_SCHOOL' in 'field list']
¿Hay q actualizar alguna tabla?

**Comment by ecorrons** [comment]
Sí! te faltan estos parches:

https://github.com/Desarrollo-CeSPI/kimkelen/tree/master/patch/2.18.2

fijate también que seguramente tenés que aplicar alguno de la 2.18.1 si venís de la .0 vos

**Comment by nfuerte** [comment]
Si, ya encontré el patch de la 2.18.2. Tb 2.18.1.
Me queda este error:
Fatal error: Declaration of BaseSchoolBehaviour::getAvailableStudentsForDivisionCourseSubject() must be compatible with that of InterfaceSchoolBehaviour::getAvailableStudentsForDivisionCourseSubject() in C:\xampp\htdocs\kimkelen-2.18.4\lib\school_behaviour\base\BaseSchoolBehaviour.class.php on line 22

**Comment by nfuerte** [comment]
Buen dia!
¿Alguna sugerencia?
Gracias!!!

**Comment by ecorrons** [comment]
Fijate de ir al archivo ´ /lib/school_behaviour/base/interface/InterfaceSchoolBehaviour.class.php ´  y en la línea 22, la firma del método (el encabezado) llamado getAvailableStudentsForDivisionCourseSubject fijate que te quede así:

  public function getAvailableStudentsForDivisionCourseSubject(CourseSubject $course_subject, $criteria = null, $filter_by_orientation = true)

Diría que es eso.
Lo voy a a arreglar para la próxima versión, ha quedado mal.

**Comment by nfuerte** [comment]
Gracias!! Sin problemas (por el momento)!
Corregi el encabezado en la linea 124 (le faltaba '= true').
