### ISSUE TITLE
no aparece barra inicio - administracion

### ISSUE THREAD

**Issue by cesarcou** [Desarrollo-CeSPI/kimkelen#161]
Despues de una ardua lucha para instalar, hace un año que lo intento hoy me decidi a instalarlo y lo logre, pero ingreso como administrador y no me aparece la barra de inicio - administracion etc..aparece en blanco..
Tengo instalado en un xampp, que puede estar faltandome..

**Comment by ncuesta** [comment]
@cesarcou El problema seguramente es que te faltan los links simbólicos a los assets. Ejecutaste todos los pasos de la instalación? Principalmente, ¿ejecutaste esto?:

```bash
$ ./symfony plugin:publish-assets
$ ./symfony kimkelen:flavor demo
```

**Comment by cesarcou** [comment]
Hola en que momento del paso lo hago, no use capistrano, ya que en el tuto que esta aqui figura esos comandos cuando usas capistrano...cuando ejecuto larga errores, voy a intentar devuelta con una instalacion de cero..
Una duda en el propel.ini donde dice propel:project alumnos, vi que en el propel dice conservatorio sino me equivoco, que debo poner, soy del interior de corrientes y mi colegio quiere implementar algun soft para administrar y este es el que me parecio mejor, pero es muy dificil instalarlo.
Voy a intentar devuelta una lastima que la Unlp no de mejores tutos o lo haga mas simple, no todos tenemos el mismo nivel de conocimientos..
Muchas gracias por contestar, estare probando.

**Comment by chrodriguez** [comment]
Lo que menciona @ncuesta debés correrlo en cualquier etapa. 

El `propel.ini` donde dice conservatorio puede decir cualquier nombre. Es el nombre del proyecto y no es relevante.

Es cierto que no tenemos un buen tutorial, pero es complicado destinarle mucho más tiempo al proyecto en este sentido. Está en nuestros planes mejorar la documentación y simplificar la distribución. Gracias por el aporte!

Saludos
