### ISSUE TITLE
Error en actualizacion a 2.19.2

### ISSUE THREAD

**Issue by nfuerte** [Desarrollo-CeSPI/kimkelen#169]
Buen dia!
Estoy actualizando el versionado de 2.18.4 a 2.19.2 y me ha dado el siguiente error:

C:\xampp\htdocs\kimkelen-2.19.2>c:/xampp/php/php symfony propel:build-forms
>> propel    generating form classes

Parse error: parse error in C:\xampp\htdocs\kimkelen-2.19.2\lib\model\CourseSubj
ect.php on line 772

**Comment by ncuesta** [comment]
@nfuerte ¿Qué versión de PHP estás usando?

**Comment by nfuerte** [comment]
PHP 5.2.8

**Comment by ncuesta** [comment]
El problema es que en la línea 772 del archivo que indica el error se está usando una expresión que es válida a partir de PHP 5.3.0 (ver [la documentación de PHP](http://php.net/manual/es/language.oop5.constants.php) para un ejemplo). Ahora actualizamos el código para que sea compatible con PHP 5.2.

**Comment by ncuesta** [comment]
@nfuerte ¿Podés probar con la nueva release v2.19.3?

**Comment by nfuerte** [comment]
Si, ahora lo descargo.
Gracias!

**Comment by nfuerte** [comment]
Instalado y funcionando.
Gracias!!!
