### ISSUE TITLE
Warning Pathway 2.19.3

### ISSUE THREAD

**Issue by nfuerte** [Desarrollo-CeSPI/kimkelen#170]
Hola!
Actualicé a 2.19.3 con windows. Durante la actualización dió algunos warnings, que ignoré, pero al entrar al sistema parece no encontrar algunas rutas. 
Con backend_dev indica:
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in C:\xampp\htdocs\kimkelen-2.19.3\lib\model\Pathway.php on line 6

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in C:\xampp\htdocs\kimkelen-2.19.3\lib\model\Pathway.php on line 11

Gracias!!!

**Comment by ncuesta** [comment]
Hola Natalia, nuevamente es un problema con la versión de PHP. Vamos a corregirlo, igualmente te recomendaría que actualices a una versión de PHP 5.3.x de ser posible.

**Comment by ncuesta** [comment]
@nfuerte Fijate con la [v2.19.4](https://github.com/Desarrollo-CeSPI/kimkelen/releases/tag/v2.19.4) por favor.

**Comment by nfuerte** [comment]
Solucionado! 
Me faltaba un patch SQL.

Gracias!

**Comment by nfuerte** [comment]
Ya lo actualizo a algun 5.3.x.
Gracias
