### ISSUE TITLE
Error al cargar datos iniciales 

### ISSUE THREAD

**Issue by zcortes** [Desarrollo-CeSPI/kimkelen#171]
He seguido los siguientes pasos para instalarlo en windows 7 professional 64 bits: 
1) Descargar y descomprimir kimkelen en xampp/htdocs/kimkelen
**Verifiqué los requisitos del sistema y su cumplimiento.**
2) Utilizé estos comandos: 
symfony kimkelen:flavor demo
symfony propel:build-model
symfony propel:build-forms
symfony propel:build-filters
symfony propel:build-sql
symfony propel:insert-sql 
symfony plugin:publish
symfony project:permissions
symfony propel:data-load
Al ingresar a /web/login me aparece el skin como el demo en linea, sin embargo **no me permite accesar con user:admin y passwd: admin ni con user: admin y passwd: @dm1n1strad0r**
Al correr los script me lanzó los siguientes errores: 
***************
[PHP Error] mysql_escape_string(): This function is deprecated; use mysql_real_e
scape_string() instead. [line 98 of C:\xampp\htdocs\kimkelen-3\lib\symfony\plugi
ns\sfPropelPlugin\lib\vendor\propel-generator\classes\propel\engine\platform\Mys
qlPlatform.php]
---->El cual solucioné abriendo el archivo y **cambiando a la sentencia mysql_real_escape_string**, para lo cual me lanzaba el siguiente error: 
PHP Error] mysql_real_escape_string(): The mysql extension is deprecated and wi
ll be removed in the future: use mysqli or PDO instead [line 98 of C:\xampp\htdo
cs\kimkelen-3\lib\symfony\plugins\sfPropelPlugin\lib\vendor\propel-generator\cla
sses\propel\engine\platform\MysqlPlatform.php]

Posteriormente en plugin:publish: 
Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\ki
mkelen-3\lib\symfony\task\sfFilesystem.class.php on line 224
>> plugin    Configuring plugin - dcStatefulSecurityPlugin
>> plugin    Configuring plugin - ncPropelChangeLogBehaviorPlugin

Y lo que ya no supe ni que hacer en propel:data-load: 
Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\ki
mkelen-3\lib\symfony\task\sfFilesystem.class.php on line 224
>> plugin    Configuring plugin - dcStatefulSecurityPlugin
>> plugin    Configuring plugin - ncPropelChangeLogBehaviorPlugin
![image](https://cloud.githubusercontent.com/assets/10969045/9015811/52c41704-3791-11e5-93eb-0393c1f6e8a3.png)

Inclusive desactivé la verificacion de llaves foraneas en mysql con 
**SET FOREIGN_KEY_CHECKS=0;** 
Por obviedad tengo instalado Xampp v.3.2.1 
Espero que su apoyo. Muchas gracias de antemano. 

![image](https://cloud.githubusercontent.com/assets/10969045/9015898/20ce9eb2-3792-11e5-8cb9-780683c02a1e.png)

**Comment by ncuesta** [comment]
Que versión de php tenes instalada?

Nahuel Cuesta Luengo
On vie, jul 31, 2015 at 4:37 p.m., Desarrollo-CeSPI/kimkelen
<reply@reply.github.com>
wrote:
He seguido los siguientes pasos para instalarlo en windows 7 professional 64
bits:
1) Descargar y descomprimir kimkelen en xampp/htdocs/kimkelen
Verifiqué los requisitos del sistema y su cumplimiento.
2) Utilizé estos comandos:
symfony kimkelen:flavor demo
symfony propel:build-model
symfony propel:build-forms
symfony propel:build-filters
symfony propel:build-sql
symfony propel:insert-sql
symfony plugin:publish
symfony project:permissions
symfony propel:data-load
Al ingresar a /web/login me aparece el skin como el demo en linea, sin embargo no me permite accesar con user:admin y passwd: admin ni con user: admin y
passwd: @dm1n1strad0r
Al correr los script me lanzó los siguientes errores:


--------------------------------------------------------------------------------

[PHP Error] mysql_escape_string(): This function is deprecated; use mysql_real_e
scape_string() instead. [line 98 of C:\xampp\htdocs\kimkelen-3\lib\symfony\plugi
ns\sfPropelPlugin\lib\vendor\propel-generator\classes\propel\engine\platform\Mys
qlPlatform.php]
---->El cual solucioné abriendo el archivo y cambiando a la sentencia mysql_real_escape_string , para lo cual me lanzaba el siguiente error:
PHP Error] mysql_real_escape_string(): The mysql extension is deprecated and wi
ll be removed in the future: use mysqli or PDO instead [line 98 of C:\xampp\htdo
cs\kimkelen-3\lib\symfony\plugins\sfPropelPlugin\lib\vendor\propel-generator\cla
sses\propel\engine\platform\MysqlPlatform.php]

Posteriormente en plugin:publish:
Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\ki
mkelen-3\lib\symfony\task\sfFilesystem.class.php on line 224

plugin Configuring plugin - dcStatefulSecurityPlugin
plugin Configuring plugin - ncPropelChangeLogBehaviorPlugin

Y lo que ya no supe ni que hacer en propel:data-load:
Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\ki
mkelen-3\lib\symfony\task\sfFilesystem.class.php on line 224

plugin Configuring plugin - dcStatefulSecurityPlugin
plugin Configuring plugin - ncPropelChangeLogBehaviorPlugin
image
[https://cloud.githubusercontent.com/assets/10969045/9015811/52c41704-3791-11e5-93eb-0393c1f6e8a3.png]
[https://cloud.githubusercontent.com/assets/10969045/9015811/52c41704-3791-11e5-93eb-0393c1f6e8a3.png]

Inclusive desactivé la verificacion de llaves foraneas en mysql con
**SET FOREIGN_KEY_CHECKS=0;
Por obviedad tengo instalado Xampp v.3.2.1

—
Reply to this email directly or view it on GitHub [https://github.com/Desarrollo-CeSPI/kimkelen/issues/171] .[https://github.com/notifications/beacon/AAF1aIa1rL55QkKtcUid0N6uJcYSeH5yks5oi8XbgaJpZM4FjtrI.gif]

-----
CeSPI 
Centro Superior para el Procesamiento de la Informaci�n

Universidad Nacional de La Plata
-------------------------------------------------------------------------------
Proteja el Medioambiente. No imprima este mail si no es absolutamente necesario

**Comment by zcortes** [comment]
![image](https://cloud.githubusercontent.com/assets/10969045/9016181/888403ba-3794-11e5-86c1-9c7f3b242899.png)

Creo que el error es ese. Verificando con c:\xampp\php\php ./data/symfony/bin/check_configuration.php da una OK pero con php --version da una versión diferente. 
Verificaré con un xampp con versión de php menor y comentaré los resultados.

**Comment by zcortes** [comment]
Instalé la version de xampp 1.7.7 sin embargo al colocar el "sabor" demo, me aparece:
**The application "backend" does not exist. **

**Comment by ncuesta** [comment]
Chequea que el código del proyecto este bien, y que la versión de PHP sea
correcta (no sé qué versión de PHP trae ese Xampp)

Nahuel Cuesta Luengo
On vie, jul 31, 2015 at 6:43 p.m., Desarrollo-CeSPI/kimkelen
<reply@reply.github.com>
wrote:
Instalé la version de xampp 1.7.7 sin embargo al colocar el "sabor" demo, me
aparece:
* The application "backend" does not exist. *

—
Reply to this email directly or view it on GitHub
[https://github.com/Desarrollo-CeSPI/kimkelen/issues/171#issuecomment-126819623] .[https://github.com/notifications/beacon/AAF1aHd5kPE5LjXVbMov9rBmF0jKmwzWks5oi-OdgaJpZM4FjtrI.gif]

-----
CeSPI 
Centro Superior para el Procesamiento de la Informaci�n

Universidad Nacional de La Plata
-------------------------------------------------------------------------------
Proteja el Medioambiente. No imprima este mail si no es absolutamente necesario

**Comment by zcortes** [comment]
Esta version (1.7.7) incluye:    
    - Apache 2.2.21
    - MySQL 5.5.16
    - PHP 5.3.8
    - Perl 5.10.1
    - ProFTPD 1.3.3e
    - phpMyAdmin 3.4.5
Hasta ahora, lo que he intentado es desactivar el control parental (UAC) con lo que se soluciona el problema anterior, sin embargo, al llegar al **symfony propel:data-load** sigue presentándose el siguiente error: 
[propel-sql] Could not perform XLST transformation.  Make sure PHP has been comp
iled/configured to support XSLT.

Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\ki
mkelen\lib\symfony\task\sfFilesystem.class.php on line 224

c:\xampp\htdocs\kimkelen>c:\xampp\php\php.exe symfony propel:data-load
>> propel    load data from "C:/xampp/htdocs...uardSecurePlugin/data/fixtures"
>> propel    load data from "C:/xampp/htdocs/kimkelen/data/fixtures"
**Unable to execute INSERT statement. [wrapped: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-112' for key 'PRIMARY']**
No menciona que tabla tiene la duplicidad, inclusive intenté desactivando la verificacion de llaves foraneas con: 
SET FOREIGN_KEY_CHECKS=0;
pero tampoco funcionó... 
El login me aparece como el demo en linea (que por cierto, esta marcando error 500) sin embargo no permite accesar con los datos que estan en INSTALL o README.

**Comment by ncuesta** [comment]
El tema es que estas intentando popular la base con datos cuando esta ya los
tiene. Borra la base de datos, créala de nuevo y volve a correr
elpropel:data-load.
El resto de los warnings podes ignorarlos.

Nahuel Cuesta Luengo
On vie, jul 31, 2015 at 7:48 p.m., Desarrollo-CeSPI/kimkelen
<reply@reply.github.com>
wrote:
Esta version (1.7.7) incluye:

- Apache 2.2.21
- MySQL 5.5.16
- PHP 5.3.8
- Perl 5.10.1
- ProFTPD 1.3.3e
- phpMyAdmin 3.4.5
Hasta ahora, lo que he intentado es desactivar el control parental (UAC) con lo
que se soluciona el problema anterior, sin embargo, al llegar al symfony propel:data-load sigue presentándose el siguiente error:
[propel-sql] Could not perform XLST transformation. Make sure PHP has been comp
iled/configured to support XSLT.

Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\ki
mkelen\lib\symfony\task\sfFilesystem.class.php on line 224

c:\xampp\htdocs\kimkelen>c:\xampp\php\php.exe symfony propel:data-load

propel load data from "C:/xampp/htdocs...uardSecurePlugin/data/fixtures"
propel load data from "C:/xampp/htdocs/kimkelen/data/fixtures"
Unable to execute INSERT statement. [wrapped: SQLSTATE[23000]: Integrity
constraint violation: 1062 Duplicate entry '2-112' for key 'PRIMARY']
No menciona que tabla tiene la duplicidad, inclusive intenté desactivando la
verificacion de llaves foraneas con:
SET FOREIGN_KEY_CHECKS=0;
pero tampoco funcionó...
El login me aparece como el demo en linea (que por cierto, esta marcando error
500) sin embargo no permite accesar con los datos que estan en INSTALL o README.

—
Reply to this email directly or view it on GitHub
[https://github.com/Desarrollo-CeSPI/kimkelen/issues/171#issuecomment-126829910] .[https://github.com/notifications/beacon/AAF1aAgefn0mGBBR2drFEJzoe1zaQNz6ks5oi_K4gaJpZM4FjtrI.gif]

-----
CeSPI 
Centro Superior para el Procesamiento de la Informaci�n

Universidad Nacional de La Plata
-------------------------------------------------------------------------------
Proteja el Medioambiente. No imprima este mail si no es absolutamente necesario

**Comment by zcortes** [comment]
Lo acabo de realizar. Borré la BD con phpmyadmin, la creé nuevamente (sin tablas, claro) y corrí solamente symfony propel:data-load sin embargo lanzaba el siguiente error: 
*Base table or view not found: 1146 Table 'kimkelen.personal' doesn't exist.*
Asi que corri propel:build-sql y propel:insert-sql; despues propel:data-load y el mismo error. 
**Unable to execute INSERT statement. [wrapped: SQLSTATE[23000]: Integrity
constraint violation: 1062 Duplicate entry '2-112' for key 'PRIMARY']**

**Comment by zcortes** [comment]
Utilicé kimkelen 2.19.3 y realicé los pasos anteriores, sin embargo no permite cargar los datos iniciales y tampoco permite el logeo.

**Comment by ncuesta** [comment]
Esos errores indican que ya hay datos en la base, tiene que venir por ese lado el problema. No se me ocurre otro problema, te recomendaría que veas de revisar lo relacionado a la base o si no que comiences de nuevo con una instalación de cerro.
