### ISSUE TITLE
Problemas con la configuracion de Apache

### ISSUE THREAD

**Issue by sebastiancorrea81** [Desarrollo-CeSPI/kimkelen#174]
Buenos Dias, estoy teniendo problemas con la configuracion de apache, ya que corro todos los comandos sin ningun problema, al logearme me aparece el error 404, leyendo e investigando los issues 17 y 50, se debe a que apache no esta configurado el mod_rewrite. Verificando el mod lo tengo habilitado, lo que no lo tengo es en el virtual host. Cree un virtual host para kimkelen tomando como ejemplo el que esta en el proyecto. Al reiniciar apache me da error. Alguna sugerencia? Gracias

**Comment by ncuesta** [comment]
Hola @sebastiancorrea81, ¿podrás copiar el error así intentamos ayudarte con eso?

**Comment by sebastiancorrea81** [comment]
Hola gracias por la pronta respuesta
este es el error
[....] Reloading apache2 configuration (via systemctl): apache2.serviceJob for apache2.service failed    . See 'systemctl status apache2.service' and 'journalctl -xn' for details.
 failed!
esta es la configuracion de apache
<VirtualHost *:80>
ServerAdmin     webmaster@localhost
DocumentRoot    /var/www/html/kimkelen/web
ErrorLog        ${APACHE_LOG_DIR}/error.log
CustomLog       ${APACHE_LOG_DIR}/access.log combined
<Directory /var/www/html/kimkelen/web >
Options -Indexes FolloSymLinks -MultiViews
AllowOverride None
Order allow,deny
allow from all
</Directory>
</VirtualHost>
De todas formas si yo tengo bien habilitado el virtual host, cuando por el navegador ingreso ipservidor/kimkelen esto deberia llevarle directamente al login?? es asi?
Gracias

**Comment by chrodriguez** [comment]
@sebastiancorrea81 podrías pasar el error que da Apache? Como sugiere el mensaje que pagaste, tal vez te lo de 'systemctl status apache2.service' 

Sino en donde la configuracion de apache escriba los logs de error. Generalmente /var/log/apache2/error.log

Saludos

**Comment by sebastiancorrea81** [comment]
Muchas Gracias por la respuesta, el problema era que al hacer login daba el error 404, habilite el mod_rewrite en apache como lei en otros issues y aun asi seguia fallando, entonces en el 000-default.conf cambie el DocumentRoot para que punte a kimkelen/web, esto para asegurarme que estaba bien la ruta. El archivo 000-default.conf me quedo asi
 <VirtualHost *:80>
 ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/kimkelen/web
        RewriteEngine On
        <Directory /var/www/html/kimkelen/web >
        AllowOverride All
        </Directory>
</VirtualHost>
Creo que el problema era o que no estaba leyendo bien el .htaccess o que no quedaba bien habiltado el .conf que habia hecho antes.

Muchas Gracias por la pronta repuesta!!!!!!

**Comment by sebastiancorrea81** [comment]
Perdon no se copio bien la configuracion de 000-default.conf quedo asi

ServerAdmin webmaster@localhost
DocumentRoot /var/www/html/kimkelen/web
RewriteEngine On
<Directory /var/www/html/kimkelen/web >
AllowOverride All
</Directory>
Gracias de nuevo!!!

**Comment by ncuesta** [comment]
Excelente si pudiste arreglarlo! Saludos!
