### ISSUE TITLE
Consultas Varias sobre la configuracion de Apache

### ISSUE THREAD

**Issue by sebastiancorrea81** [Desarrollo-CeSPI/kimkelen#175]
Buenas tardes, logre hacer funcionar la palicacion y corre todo perfecto. Pero me queda una duda que despues de haber googleado no logro responder, y tal vez se debe a mi poco conocimiento de apache. La duda es la siguiente, en mi carpeta de apache/sites-availables yo tengo un 000-default.conf y cree otro archivo kimkelen.conf en donde puse toda la configuracion de kimkelen, con esta configuracion no funciona, pero si yo pongo la configuracion de kimkelen en el 000-default corre si problemas. Alguna idea de por que puede pasar esto? Seta que tambien tengo que habilitar en el /etc/host???. Garcias

**Comment by ncuesta** [comment]
@sebastiancorrea81 te está faltando *habilitar* el vhost. Podés ver [acá](https://www.digitalocean.com/community/tutorials/como-configurar-virtual-host-de-apache-en-ubuntu-14-04-lts-es#paso-cinco-—-habilita-los-nuevos-archivos-virtual-host) cómo habilitarlos. El directorio `apache/sitest-available` contiene los sitios *disponibles* para que Apache sirva, mientras que `apache/sites-enabled` contiene los que serán efectivamente servidos.
