### ISSUE TITLE
URGENTE - Materias y talleres optativos

### ISSUE THREAD

**Issue by sexto** [Desarrollo-CeSPI/kimkelen#176]
Hola! Les escribimos porque tenemos inconvenientes en la creación de materias y talleres optativos del segundo cuatrimestre para 6° año del Liceo Víctor Mercante. Gracias!

**Comment by ecorrons** [comment]
Me voy a poner en contacto con uds para que me cuenten bien qué problema tienen.
Saludos

**Comment by sexto** [comment]
Gracias!!
Saludos!

Quoting María Emilia Corrons <notifications@github.com>:

> Me voy a poner en contacto con uds para que me cuenten bien qué  
> problema tienen.
> Saludos
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Desarrollo-CeSPI/kimkelen/issues/176#issuecomment-144436601



----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.
