### ISSUE TITLE
URGENTE - Para Emilia

### ISSUE THREAD

**Issue by sexto** [Desarrollo-CeSPI/kimkelen#177]
Hola Emilia! Tal como nos solicitaron desde Cespi, enviamos el reporte de los sucedido con las materias y talleres optativos de 6° año del LVM: Al cargar las materias ingresamos en un ítem donde se generaron automáticamente 45 materias. No pudimos revertirlo con ningún usuario, ni siquiera con  el de la Secretaria de Dirección. Gracias!! Saludos!

**Comment by ecorrons** [comment]
Ya está solucionado. Saludos!

**Comment by sexto** [comment]
Hola Emilia, surgio otro inconveniente, en naturales Genética que es  
materia orientadora y debería aparecer en comisión aparece en división  
y no me deja borrarla.
en Gestión ocurre lo mismo con Psicología social y organizacional.
Y por último no podemos generar economía para Sociales que también  
tiene que ir en comisión
te agradezco, saludos
                           Mariana



----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.

**Comment by ecorrons** [comment]
Hola Mariana, la comisión de economía ya la veo creada... crearon 3 de hecho.
Ya está arreglado lo de Genética.

**Comment by sexto** [comment]
Hola Emilia! No podemos ver la materia Economía ni Genética Humana.  
Por favor, ¿podrías administrarnos como preceptores a: Lucía Quenard y  
Marialina Pedrini? Quizás no nos figure por eso.
Perdón por la molestia! Esperamos resolverlo pronto!!
Saludos!
Preceptoría 6° - LVM

----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.

**Comment by ecorrons** [comment]
Economía está creada como COMISION, fijense ahí. Si la quieren crear en una división no les deja porque en la configuración Economía está puesta como opción de Optativa. Entonces la van a poder crear dentro de Materia Optativa I o II.
