### ISSUE TITLE
Problemas con la Instalacion en Windows 8.1 64 bits

### ISSUE THREAD

**Issue by ledesmafabio** [Desarrollo-CeSPI/kimkelen#193]
Hola, hace 3 dias que estoy intentando instalar el kimkelen 2.20.4 en mi computadora y no se que hago mal, los pasos fueron estos:
* Instale el XAMPP 1.8.3 (por si habia problemas de version con el kimkelen) en el disco D
* Cree la base de datos (la llame kimkelen) con el phpmyadmin
* Copie la carpeta kimkelen en el directorio htdocs de XAMPP
* Configure los archivos: databases.yml y propel.ini con NotePad++ segun el tutorial
* Problema 01: Funcion Deprecated preg_replace() lo solucione actualizando los archivos de symfony manualmente, con el detalle de que en mi PC no existia el archivo "sfFormObject.class.php" asi que lo generé yo con la función solicitada y lo puse en la carpeta symfony\form\
* Problema 02: unable to create symlink(), encontre que cambiando las propiedades del php.exe a compatibilidad con Windows XP se solucionaba, lo hice y no saltó mas el error.
* Corri el comando "./data/symfony/bin/check_configuration.php" que me devolvió todo ok, solo me pidio instalar el php acelerator APC lo que me llevó al
* Problema 03: al querer instalar el APC, probe con un monton de versiones y ninguna me permitió seguir con la instalacion, asi que lo descarte (no se si era obligatorio)
* Problema 04: error deprecated function "mysql_escape_string()", encontre que había que actualizar el archivo MysqlPlatform.php cambiando la sentencia original por return mysqli_real_escape_string($text); no tiró mas error.
* Ejecute symfony kimkelen:flavor demo sin problemas
* Problema 05: Como no pude ejecutar el comando symfony propel:buil-all-load sin que se trabara (ahi estoy igual) lo cambie por la ejecucion de los comandos internos uno a uno pare ver donde estaba el error.
*  ./symfony propel:build-model sin problemas
*  ./symfony propel:build-forms sin problemas
*  ./symfony propel:build-filters sin problemas
*  ./symfony propel:build-sql sin problemas
*  ./symfony propel:insert-sql  comienza y se detiene en: propel running "insert-sql" phing task
* Problema 06: Lei por ahi que podría ejecutar primero "php symfony plugin:publish" por si era un tema de plugins ahi me encontré con que hay archivos que no existen destro de la carpeta plugins pero relacionados a imagenes y themes y como son solo "warnings" los obvié.

Bueno ante todo me disculpo por lo extenso, pero trate de ser lo más explícito posible, para que me ayuden a encontrar cual de todos los pasos es el que en realidad no me está dejando terminar con la instalación. Y la verdad es que ya pase muchas horas sin encontrarle la vuelta.

**Comment by chrodriguez** [comment]
Hola @ledesmafabio, por lo que veo en: <https://www.apachefriends.org/blog/news-article-232017.html>

Esta versión de XAMPP usa PHP 5.5.6. Como dice el [INSTALL](https://github.com/Desarrollo-CeSPI/kimkelen/blob/master/INSTALL) de kimkelen, este producto funciona sobre PHP versión < 5.4. 

Porbá bajando la versión de XAMPP y probá nuevamente

Saludos
