### ISSUE TITLE
Exportar Tutores

### ISSUE THREAD

**Issue by claudiokum** [Desarrollo-CeSPI/kimkelen#197]
Al exportar los tutores a un Excel, el nombre del tutor se repite en la columna A Cargo (lugar donde debería de figurar el nombre del alumno que tiene a cargo el tutor). Error que viene desde versiones viejas. Gracias

**Comment by palmegonzalez** [comment]
Buenos dias @claudiokum, este error fue evaluado y solucionado, con la ultima actualizacion del sistema deberias tener corregido el problema. 

Saludos.
