### ISSUE TITLE
Mesas de Exámenes Automaticas

### ISSUE THREAD

**Issue by claudiokum** [Desarrollo-CeSPI/kimkelen#200]
Disculpen las molestias. Tengo corriendo el sistema en una secundaria técnica, y nose si alguno ya se lo planteo. En la instancia de diciembre y marzo aca son mesas donde el profesor del curso es el responsable. Cuando se crea las mesas en esas instancias de deverian crear por curso/div no por materia. Es que cada profesor deveria de entrar y tan solo ver su mesas y sus alumnos nada mas. Ejemplo: Tengo Lengua de 1º1º y Lengua de 1º2º con profesores distintos cada uno tendría que entrar a su mesa y visualizar su curso y sus alumnos no ver el del otro curso. Mil disculpas las molestias estoy estudiando para corregirlo en mi caso. Pero si ya alguno tiene una solución MIL gracias.

**Comment by palmegonzalez** [comment]
@claudiokum por el momento el sistema arma las mesas por año y por materia, no esta pensando por ahora modificar esta forma de generarlas. De todas formas queda tu propuesta para charlar en un futuro.

Saludos.

**Comment by palmegonzalez** [comment]
Buenos dias @claudiokum, efectivamente las mesas se crean por año y materia y no por division el planteo inicial fue desarrollado asi y no tenemos otra solución desarrollada al momento.
Para modificar esto te diria que mires en el modulo examination, el metodo createExaminationSubject, que es donde se crean las mesas. 

Saludos.
