### ISSUE TITLE
Problemas de instalacion en Debian 8 

### ISSUE THREAD

**Issue by github-ar** [Desarrollo-CeSPI/kimkelen#206]
Estoy recibiendo el siguiente error al ejecutar -> php symfony propel:build-model

>> propel    Running "om" phing task
PHP Strict Standards:  Declaration of UnixFileSystem::getBooleanAttributes() should be compatible with FileSystem::getBooleanAttributes($f) in /var/www/html/lib/symfony/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 278
[PHP Error] Non-static method DOMDocument::load() should not be called statically, assuming $this from incompatible context [line 442 of /var/www/html/lib/symfony/plugins/sfPropelPlugin/lib/vendor/propel-generator/classes/propel/phing/AbstractPropelDataModelTask.php]
----

No es si esta faltando algun plugin, o es una incompatibildad entre versiones. 
El check configuration da todo OK. El servidor esta instalado de 0 y no comparte aplicaciones.

PHP version: PHP 5.6.17-0+deb8u1
Symfony: 1.2.13-DEV
Debian: 8.3

**Comment by ncuesta** [comment]
Hola, el problema es que Kimkelen no es compatible con versiones de PHP
posteriores a la 5.3..
Saludos

Nahuel Cuesta Luengo Desarrollo • CeSPI
On dom, mar 6, 2016 at 11:10, github-ar <notifications@github.com> wrote:
Estoy recibiendo el siguiente error al ejecutar -> php symfony
propel:build-model

propel Running "om" phing task
PHP Strict Standards: Declaration of UnixFileSystem::getBooleanAttributes()
should be compatible with FileSystem::getBooleanAttributes($f) in
/var/www/html/lib/symfony/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php
on line 278

[PHP ERROR] NON-STATIC METHOD DOMDOCUMENT::LOAD() SHOULD NOT BE CALLED
STATICALLY, ASSUMING $THIS FROM INCOMPATIBLE CONTEXT [LINE 442 OF
/VAR/WWW/HTML/LIB/SYMFONY/PLUGINS/SFPROPELPLUGIN/LIB/VENDOR/PROPEL-GENERATOR/CLASSES/PROPEL/PHING/ABSTRACTPROPELDATAMODELTASK.PHP]
No es si esta faltando algun plugin, o es una incompatibildad entre versiones.
El check configuration da todo OK. El servidor esta instalado de 0 y no comparte
aplicaciones.

PHP version: PHP 5.6.17-0+deb8u1
Symfony: 1.2.13-DEV
Debian: 8.3

—
Reply to this email directly or view it on GitHub [https://github.com/Desarrollo-CeSPI/kimkelen/issues/206] .[https://github.com/notifications/beacon/AAF1aMNtprJVwulcdLQ2Q1Gg2U_uL9nRks5pquBygaJpZM4HqQ3Y.gif]

-----
CeSPI   
Centro Superior para el Procesamiento de la Información

Universidad Nacional de La Plata
-------------------------------------------------------------------------------
Proteja el Medioambiente. No imprima este mail si no es absolutamente necesario
