### ISSUE TITLE
Instalacion de Kimkelen

### ISSUE THREAD

**Issue by rubendariodiez** [Desarrollo-CeSPI/kimkelen#212]
hola! baje Kimkelen 2.21.1, instale xampp 5.5.24, configure todo como corresponde, luego en la carpeta htdocs de xampp descomprimí la carpeta kimkelen, luego en la carpeta config modifique los archivos databases y propel renombrándolos y sacando default, colocando el nombre de la base de datos, usuario root, en localhost, la contraseña correspodiente a la base, abro ej navegador (localhost/kimkelen/) y no logro hacerlo funcionar, solo veo carpetas y archivos!
que es lo que estoy haciendo mal o no haciendo?
desde ya muchas gracias!

**Comment by claudiokum** [comment]
Estimado proba localhost/kimkelen/web/ .Si funciona, luego tendrías que configurar tu Apache del xampp.

**Comment by jolivera538** [comment]
Hola. Le cuento que estoy tratando de instalar kimkelen y no puedo alguien me puede ayudar. Copio el error.
![error](https://cloud.githubusercontent.com/assets/21071062/18516486/9a1da198-7a6f-11e6-8df7-70bfac10c130.png)

Gracias!!!

**Comment by ecorrons** [comment]
@jolivera538 no está creada una tabla en la base de datos que tiene que ver con el _login_ de usuarios.

**Comment by ecorrons** [comment]
Se relaciona con: https://github.com/Desarrollo-CeSPI/kimkelen/issues/237
