### ISSUE TITLE
Cierre Ciclo Lectivo.

### ISSUE THREAD

**Issue by claudiokum** [Desarrollo-CeSPI/kimkelen#217]
Estimado @palmegonzalez tenes razón en lo que me comentaste en el Pull #211 . En esta escuela existes previas antes del cierre del ciclo lectivo. Según lo que me decís tendría que generar un código que me borre de la tabla studen_examination_repproved_subject los alumnos que tengan mas de dos previas según se configuro en el sistema y luego que me borre de la tabla studen_repproved_course_subjet. Si es que podes como veo que andas mucho en este algún código de ejemplo como para poder realizar, me seria de mucha ayuda. Gracias

**Comment by palmegonzalez** [comment]
@claudiokum disculpa por las demoras, lo pudiste solucionar?, lo que deberias borrar de la tabla student_examination_repproved_subject son todos los alumnos que quieras hacer repetir y aparezcan en esta tabla asociados con materias del mismo año que va a repetir.

**Comment by claudiokum** [comment]
Estimado @palmegonzalez la verdad todavía no es que tengo que ver como confeccionar el código y donde insertarlo. Supongo que la función tendría que estar antes de que borre la tabla studen_repproved_course_subjet. Si podrías pasarme una pequeña ayuda de como empezar el código te agradecería un montón. La verdad no soy amante de PHP. Mil gracias y disculpa las molestias.
