### ISSUE TITLE
Error al Copiar un plan de estudios

### ISSUE THREAD

**Issue by jpablop** [Desarrollo-CeSPI/kimkelen#26]
Al intentar copiar el plan de estudios, tira un mensjae de error por memoria o duplicidad de claves .
Aparentemente intenta seguir copiando mas alla del plan de estudios (alumnos en materias, notas, etc, etc) lo que NO seria copiar el plan.
Esta funcionalidad hay q analizarla y mejorarla

**Comment by ecorrons** [comment]
fixed
