### ISSUE TITLE
Link a la mesa de ayuda

### ISSUE THREAD

**Issue by jpablop** [Desarrollo-CeSPI/kimkelen#27]
El link hoy en dia lleva a nuestra mesa de ayuda, que solo sirve para los colegios que mantenemos nosotros, en todos los otros casos debería llevar a github.

Hacer que por defecto lleve a github y que si aparece un parametro en el app.yml lleve a ese parametro (lo usariamos para nuestra mesa de ayuda)

**Comment by leandroe** [comment]
Hola andrecitwo, estoy renegando con Kimkelen para instalarlo en Linux. Uso Xampp. ¿Podrías decirme cómo hiciste para instalarlo?

**Comment by chrodriguez** [comment]
@leandroe leíste las instrucciones para la instalación disponible en: https://github.com/Desarrollo-CeSPI/kimkelen/blob/master/INSTALL
