### ISSUE TITLE
Creación de usuarios

### ISSUE THREAD

**Issue by d9000** [Desarrollo-CeSPI/kimkelen#306]
Estoy tratando de implementar el sistema en un Instituto Superior, en Ushuaia. Tengo instalado el sistema y ejecutanodose pero sin los datos que se generan a través de symfony propel:data-load (no pude ejecutarlo sin errores).
Agradecería me indiquen si existe alguna forma de crear usuarios, sobre todo administrador. Por linea de comandos o a través de la base de datos o algún script php
El sistema: xampp 1.7.7 - php 5.3.8 - Windows 10 x64

**Comment by chrodriguez** [comment]
¿Podrías mostrarnos los errores que estás teniendo?

**Comment by ecorrons** [comment]
Hola @d9000 si podés pegar aquí el log del error sería útil.
Además, ¿con qué versión (tag) del sistema estás probando?

**Comment by d9000** [comment]
Anexo una captura de pantalla. Gracias
![image](https://cloud.githubusercontent.com/assets/22692028/19393964/6ad64272-920d-11e6-9f64-f6dd9de06f2f.png)

**Comment by d9000** [comment]
Hola @ecorrons, el único log que encontre, en la carpeta log

`
Oct 08 00:26:55 symfony [err] {sfGuardSecurePlugin} Login failed for user=admin ip=::1
Oct 08 00:41:49 symfony [err] {sfGuardSecurePlugin} Login failed for user=admin ip=::1
Oct 08 00:54:02 symfony [err] {sfGuardSecurePlugin} Login failed for user=admin ip=::1
`
la versión que estoy ejecutando es la 2.20.6

Gracias

**Comment by d9000** [comment]
Solucionado, hice `truncate` de todas las tablas y `SET GLOBAL sql_mode=''` y se ejecutó el `symfony propel:data-load` sin problemas. Pude aceder al sistema con el usuario admin y la contraseña que se genera.

**Comment by ecorrons** [comment]
Genial! eso mismo había encontrado con relación a ese error y me ganaste de mano.
