### ISSUE TITLE
Administrar Alumnos en Mesa de Examen 

### ISSUE THREAD

**Issue by diegorobador1** [Desarrollo-CeSPI/kimkelen#363]
Buen día estimados, tengo el siguiente inconveniente a la hora de querer agregar alumnos, del ultimo año, en materias de la mesa de Febrero.
Cargue la nota en la mesa de examen de diciembre como ausente y cerre la mesa:

![captura2](https://cloud.githubusercontent.com/assets/26546139/24103057/d641def2-0d5c-11e7-8812-5f98bd2ae356.JPG)

Luego fui a la mesa de febrero para agregar a la alumna y no me figura:

![captura1](https://cloud.githubusercontent.com/assets/26546139/24102930/4f1b89e6-0d5c-11e7-9bf6-ff127ff30955.JPG)

Al ser una sola alumna que debía agregar, se me ocurrió modificar la nota de la mesa de febrero individualmente. Busque la alumna, seleccione editar en la materia correspondiente, agregue la nota y me sale el siguiente error:

![captura3](https://cloud.githubusercontent.com/assets/26546139/24103227/63e740bc-0d5d-11e7-893e-9e80d2f4f8fa.JPG)

Lo cual me esta validando el numero en punto flotante. Anteriormente habíamos podido solucionar ese error cuando **cargamos las notas del trimestre** modificando la clase que esta en lib/form/custom/StudentEditHistoryForm.class.php
linea 72 aprox.

cambiar el validador:

sfValidatorInteger

por uno: sfValidatorNumber

Habrá otra clase que se deba modificar para solucionar ese problema?

Gracias!

**Comment by ecorrons** [comment]
Hola @diegorobador1 ! Lo que podés hacer para estar seguro que no hay otro validador de tipo numérico en todo el sistema es tirar una búsqueda dentro de toda la carpeta de kimkelen por "`sfValidatorInteger`", y en todo lugar que encuentres que valide un campo de algún formulario que tenga que ver con **Mark/Marks** deberías reemplazarlo por uno `sfValidatorNumber` . 

Otra cosa que noto de todas formas en tus impresiones de pantalla es que la nota que le estás editando a ese alumno es una nota de diciembre y no de febrero.
Habría que ver bien si se generó correctamente en la base de datos la fila en la tabla que indica que un alumno está en febrero en una materia dada. Para eso podés consultar en la base de datos:

`SELECT * FROM  `course_subject_student_examination` WHERE course_subject_student_id = <tu_id>`

El id de la cursada en cuestión (Lengua y Literatura VI de un alumno en particular es el nro que se muestra en la barra de navegación cuando estás visualizando la última impresión de pantalla que adjuntaste aquí. Ese numero es el id para usar en la consulta SQL.
Si luego de esa consulta a la BBDD no obtenés una fila resultado que tenga en el campo `examination_number` un número `2`, quiere decir que por alguna razón ese alumno no fue enviado a febrero. Y deberías crear esa tupla a mano para que te aparezca para ser anotado en mesas de febrero.

**Comment by diegorobador1** [comment]
Buenisimo, muchisimas gracias! ya solucionamos el problema.
