### ISSUE TITLE
Eliminar Materias Cerradas en Mesas de Examen

### ISSUE THREAD

**Issue by diegorobador1** [Desarrollo-CeSPI/kimkelen#367]
Buenas tardes estimados, nuevamente los molesto consultado si se puede eliminar o volver atrás una materia cerrada de una mesa de examen.

La versión que estamos utilizando es la  2.20.6.

Gracias.

**Comment by ecorrons** [comment]
Hola @diegorobador1 no se pueden re abrir mesas cerradas desde sistema.
Desde base de datos podés hacerlo poniendo el campo is_closed de la examination_subject correspondiente en 0.
`UPDATE examination_subject SET is_closed = 0 WHERE id = XXX;`
