### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by Betarte** [Desarrollo-CeSPI/kimkelen#383]
#Error 1
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
8554395 bytes) in C:\xampp\htdocs\alumno\lib\symfony\yaml\sfYamlParser.class.ph
 on line 521
 este error no salta cuando corro las siguentes rutinas:

php symfony propel:build-model
php symfony propel:build-forms
php symfony propel:build-filters
php symfony propel:build-sql
php symfony propel:insert-sql

# Error 2
son varios errores los borre para resumir.
 C:\xampp\htdocs\alumno>php symfony plugin:publish

Warning: unlink(C:\xampp\htdocs\alumno\web\sfPropelPlugin): Permission denied in
 C:\xampp\htdocs\alumno\lib\symfony\task\sfFilesystem.class.php on line 213

Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\al
umno\lib\symfony\task\sfFilesystem.class.php on line 224
>> plugin    Configuring plugin - sfProtoculousPlugin

#Error 3.
 Las bases de datos están vacías.

**Comment by chrodriguez** [comment]
Aparentemente no alcanza la memoria seteada en el php.ini, memory_limit, podes correr el comando como:
php —d memory_limit=512M ...

**Comment by Betarte** [comment]
me dice esto:
C:\xampp\htdocs\alumno\web>c:\xampp\php\php -d memory_limit=512m
Could not open input file: ùd.

**Comment by chrodriguez** [comment]
Porque copiaste y pegaste el código que escribí, y lo escribí desde mi celular con uncaracter bastante extraño. Acá lo escribo desde una PC como corresponde:

```bash
php  -d memory_limit=512M symfony ...

```

**Comment by Betarte** [comment]
gracias amigo, por ese problema no lograba avanzar hace unos tres días.
