### ISSUE TITLE
Flavor Nuevos

### ISSUE THREAD

**Issue by Betarte** [Desarrollo-CeSPI/kimkelen#384]
Cuando estoy creando un flavor nuevo, me salta estos errores:

php symfony kimkelen:create-flavor  ctpoba1

Warning: file_put_contents(C:\xampp\htdocs\alumno/flavors/ctpoba1/config/view.ym
l): failed to open stream: No such file or directory in C:\xampp\htdocs\alumno\l
ib\task\kimkelenCreateflavorTask.class.php on line 71

Warning: file_put_contents(C:\xampp\htdocs\alumno/flavors/ctpoba1/templates/layo
ut.php): failed to open stream: No such file or directory in C:\xampp\htdocs\alu
mno\lib\task\kimkelenCreateflavorTask.class.php on line 193
>> Flavor    Successfully created new flavor

**Comment by ecorrons** [comment]
Hola @Betarte ! Es un warning, no un error. Esa tarea que corriste sirve para crear el propio `flavor` de tu escuela. Lo que hace es crear una estructura esqueleto vacía dentro del directorio `flavors` , con el nombre de tu escuela. Fijate si quedó creado y comparala con algún otro flavor. Si sigue la misma estuctura está bien y sobre esas clases vos podés programar el comportamiento que necesites.
Saludos

**Comment by Betarte** [comment]
si quedo creado, yo solo copie la parte del warning.

**Comment by Betarte** [comment]
le falto crea la carpeta config y template,
 lo puedo copiar directamente de otra carpeta?

**Comment by Betarte** [comment]
la estructuras son totalmente diferentes. 
compara la carpeta cnba con la mía:
en cnba hay 187 archivos y 36 carpetas
en la nueva 4 archivos y 16 carpetas.

**Comment by Betarte** [comment]
No se si es correcto, pero modifique el kimkelenCreateflavorTask.class.php agregando esto:
$this->getFilesystem()->mkdirs($new_flavor . '/config/');
	  $this->getFilesystem()->mkdirs($new_flavor . '/lib/behavior/filter');
      $this->getFilesystem()->mkdirs($new_flavor . '/lib/behavior/form');
      $this->getFilesystem()->mkdirs($new_flavor . '/modules/course_student_mark/templates');
      $this->getFilesystem()->mkdirs($new_flavor . '/modules/report_card/templates');
      $this->getFilesystem()->mkdirs($new_flavor . '/modules/shared_course/templates');
      $this->getFilesystem()->mkdirs($new_flavor . '/modules/student/templates');
	  $this->getFilesystem()->mkdirs($new_flavor . '/templates');
	  $this->getFilesystem()->mkdirs($new_flavor . '/web/css/smoothness/images');
     y no salta mas el

**Comment by ecorrons** [comment]
Claro que otro flavor te va a dar que tiene muchos más archivos porque tiene mucha personalización.
Al decir 'la misma estructura' me refería yo al esqueleto principal. Veo ahí que copiaste directorios dentro de `modules`, quizás vos no quieras personalizar esos módulos.
Te recomiendo que leas la seccion "Flavors o sabores" de acá: https://github.com/Desarrollo-CeSPI/kimkelen/blob/master/doc/manual_desarrollo.mkd para que veas qué va en cada subdirectorio y archivo del flavor. Mientras tanto, podés probar con el sabor Demo que es un sabor base y empezar a personalizar desde ese.
Saludos
