### ISSUE TITLE
Error 500 Mailer

### ISSUE THREAD

**Issue by claudiokum** [Desarrollo-CeSPI/kimkelen#394]
Estimada @ecorrons Cuando termino de actualizar el kimkelen me sale el siguiente error:

500 | Internal Server Error | sfParseException
Configuration file "/var/www/lib/symfony/config/config/factories.yml" specifies category "mailer" with missing class key. 

Revise el archivo en cuestión pero en la instalación no agrego mailer. Podes orientarme o ayudarme. Gracias.

**Comment by ecorrons** [comment]
Hola @claudiokum ! 
Estamos por largar todo un nuevo módulo de funcionalidad y va a ser necesario agregar una nueva configuración en un archivo. Disculpa las molestias! Ya lo agregaré a los pasos de instalación para que quede documentado.
Lo que debés agregar es en el `apps/backend/config/factories.yml` una clave llamada `mailer` con algunas claves de configuración por defecto. Mira, copiá y pegá como dice aquí: 
https://symfony.com/legacy/doc/reference/1_4/en/05-Factories#chapter_05_mailer

y que por el momento no hace falta configurarlo, cuando esté lista la nueva funcionalidad si querés que la aplicación envíe e-mails si deberás configurarlo. pero por el momento con solo poner esa data en el factories.yml debería bastar.

¿Funcionó?

**Comment by claudiokum** [comment]
Hola @ecorrons 
Agregue las llaves en "apps/backend/config/factories.yml" ademas en apps/tutors_frontend/config/factories.yml y en lib/symfony/config/config/factories.yml, ya puedo entrar al sistema desde el backend sin problema pero cuando genero un user para un tutor y quiero probarlo en otro navegador con la dirección "http://localhost/tutors_frontend_dev.php" me sigue saltando el error
500 | Internal Server Error | sfParseException
Configuration file "/var/www/lib/symfony/config/config/factories.yml" specifies category "mailer" with missing class key.

Me falta algo? o estoy asiendo algo mal? gracias por contestar!!
Saludos

**Comment by claudiokum** [comment]
Estimada @ecorrons ya lo pude solucionar error de tipeo en la llave.

Gracias Saludos
