### ISSUE TITLE
Problema con Materias asignadas a Alumnos

### ISSUE THREAD

**Issue by alexisgoette** [Desarrollo-CeSPI/kimkelen#401]
Al ingresar a la opción Materias a Cursar/Administrar Materias a Cursar dentro del Listado de Alumnos para un alumno en  particular y querer guardar ocurre el siguiente error.

La pagina es la siguiente
http://localhost/kimkelen/web/backend_dev.php/student/1/manageCareerSubjectAllowed

El error es el siguiente
Fatal error: Call to a member function getId() on a non-object in C:\xampp\htdocs\kimkelen\lib\form\custom\StudentCareerSubjectAllowedManagementForm.class.php on line 118
La linea es esta
$criteria->add(PathwayPeer::SCHOOL_YEAR_ID,$sy->getId());

Me fijé en la base y el año lectivo tiene ID con valor 1

Tambien ocurre esto desde la vista Listado de Estudiantes del Año Lectivo
 En lugar de los datos del alumno aparece solo esto.
../../student/templates/_student_info.php

En la base hay un solo año lectivo, una sola carrera, una sola materia y un solo alumno. Estoy recién probando el sistema

Estoy utilizando xampp 1.7.7 y la version 2.26.5 de kimkelen

**Comment by ecorrons** [comment]
Hola @alexisgoette , te recomendaría que actualices la versión del sistema a la última, ya que ese error que decís lo solucionamos hace un tiempo. Quizás justo descargaste el tag donde sucedía...
