### ISSUE TITLE
Calificaciones por letras

### ISSUE THREAD

**Issue by ggallino** [Desarrollo-CeSPI/kimkelen#409]
Buenos días.  Estamos evaluando implementar el sistema y necesito realizar algunas consultas:

1. ¿Hay posibilidad de configurar el sistema para que las calificaciones se realicen con letras? Otra opción sería realizar una conversión al momento de Imprimir los boletines.
2.  ¿Hoy posibilidad de cargar Historicos, si es posible cargar en forma masiva datos de alumnos (calificaciones de años anteriores, etc)

Saludos

**Comment by ecorrons** [comment]
Hola @ggallino ! Gracias por tus consultas.

1. Sí, se pueden realizar calificaciones con letras. Para ello, debés configurar la/s materia/s que quieras que adopten ese comportamiento desde Académica->Años lectivos->Ver carreras->Materias y de cada materia dentro de la opción Configuración está el desplegable Tipo de nota que puede cambiarse a 'Con letras'. Si la mayoría de tus materias van a tener calificación con letras quizás te convenga cambiarlo en la configuración global de la carrera, esto sería desde Académica->Años lectivos->Ver carreras->Configuración directamente, y lo hacés cuando estés dando de alta la carrera.
Siguiente paso sería llenar a tu necesidad la tabla de la base de datos llamada `letter_mark`
por ejemplo, con el contenido: 

```INSERT INTO `letter_mark` (`id`, `letter`, `value`) VALUES (1, 'Reg.', 4),(2, 'B-', 6),(3, 'B', 7),(4, 'B+', 8),(5, 'MB', 9),(6, 'Exc.', 10);```


2. No es posible cargar históricos desde sistema. La idea es que vas cargando del año lectivo activo actual, que bien podrías arrancar cargando un año antiguo. Pero para una carga masiva desde algún planilla excel que ya tengas vos por ejemplo, no tenemos una opción por sistema. Nosotros en esos casos solemos usar herramientas como Pentaho Spoon, o SQL directamente si no es tan compleja la migración.

¡Saludos!
