### ISSUE TITLE
Plugins 

### ISSUE THREAD

**Issue by smarevalo** [Desarrollo-CeSPI/kimkelen#412]
Hola, queria consultar como se pueden desactivar algunos plugins o modificarlos, por ejemplo el sfCaptchaGDPlugin, para desactivarlo o modificar la cantidad de veces que el login debe fallar para que comience aparecer el captcha.

Desde ya muchas gracias

**Comment by ecorrons** [comment]
Hola @smarevalo ! Sí, podrías deshabilitar un plugin. Para el caso del ´sfCaptchaGDPlugin´ por ejemplo, hacé el camino inverso a los pasos que plantea el archivo ´README´ del plugin (en el directorio ´plugins/sfCaptchaGDPlugin´). Sería sacarlo de los ´enabled_modules´ del archivo ´apps/backend/config/settings.yml´ y luego sacar el widget de captcha del formulario de login.
