### ISSUE TITLE
Años lectivos

### ISSUE THREAD

**Issue by smarevalo** [Desarrollo-CeSPI/kimkelen#423]
Hola, estamos usando la version 2.20.6 y queria consultar como hacer para cargar años lectivos anteriores al presente y que a cada alumno les tome correctamente su historial, es decir si esta en 5 año, poder cargarle las notas/asistencias de las materias de 1 año hasta 4 año.

Desde ya, muchas gracias!

**Comment by ecorrons** [comment]
Hola @smarevalo ! Lamentablemente Kimkëlen no cuenta con una funcionalidad de carga histórica. Lo que nosotros usamos para tales casos son otras herramientas tales como Pentaho Spoon (http://community.pentaho.com/projects/data-integration/) que permiten migrar datos a una base de datos desde distintas fuentes, ya sean archivos exceles, otras bases de datos, etc.

¡Saludos!
