### ISSUE TITLE
Consultas Observacion, Promedio e Impresion Boletin

### ISSUE THREAD

**Issue by ggallino** [Desarrollo-CeSPI/kimkelen#439]
1. El campo Observación que se encuentra en el boletín, necesitamos poder cargarlo al final de cada Cuatrimestre independientemente si el alumno tuvo sanciones, licencias.  Te consulto porque el campo observaciones lo vemos solo en esas instancias.
2. Respecto al Promedio: Hay posibilidad que el sistema me permita editar el valor final calculado?
Por ejemplo: Tenemos configurado las siguiente calificaciones: 
NC (No Cumple): 5
AM (A mejorar): 7
S (Satisfactorio): 8
D: 10
Para un alumno X, tuvo las siguientes calificaciones:
Primer Cuatrimestre: AM
Segundo Cuatrimestre: S
El sistema asignará AM (No aprueba)
Puede suceder que al alumno se le asigne como nota final: S, ya que realizan una evaluación de concepto.
Otra posibilidad es que cambiemos las calificaciones (pero no depende de mí):
NC (No Cumple): 5
AM (A mejorar): 6
AM+ (A mejorar): 7
S (Satisfactorio): 8
S+(Satisfactorio): 9
D: 10
3. Por otro lado me arroja error al querer imprimir el Boletín:
“Se produjo un error al cargar el documento PDF”  Muestra que el PDF es de longitud 0.
¿Podrías guiarme como solucionar este problema?

**Comment by ecorrons** [comment]
Hola @ggallino ! 
1. El campo observación de los boletines lo agregamos para que sea cargado a mano. Si vos querés cargarlo tendrías que modificar el código del sistema para que tome su contenido o bien de la base de datos o que solicite ingresar texto por el usuario antes de dibujar el boletin (que se dibuja dinámicamente.

2. No se permite la edición explícita del promedio. De hecho, no es un valor que quede guardado en la base de datos, es justamente calculado a partir de las notas de cursada (course_subject_student_mark).
Las escalas de notas si las podrías modificar sin problemas.

3. Fijate si podés pasarme un log del error. Ingresar al sistema poniendo _dev.php a como estas accediendo. Por ejemplo, si ingresas como: http://tuservidor/web/kimkelen.php poné http://tuservidor/web/kimkelen_dev.php para asi ver que puede ser el error
quizás tiene que ver con tener instalado en el servidor http://code.google.com/p/wkhtmltopdf/
que es necesario para poder generar los PDF de los boletines.

**Comment by ggallino** [comment]
Muchas gracias.  Instalamos en el servidor lo que nos indicaste.  Genera el PDF pero vacío.
El log arroja:
805 | ncFlavorPartialView | Render "sf_app_dir/modules/report_card/templates/_footer.php"
806 | ncFlavorPartialView | Render "sf_app_dir/modules/report_card/templates/_quaterly_attendance_for_day.php"
807 | ncFlavorPartialView | Render "sf_app_dir/modules/report_card/templates/_signature_boxes.php"
808 | ncFlavorView | Render "sf_app_dir/templates/cleanLayout.php"
809 | WebResponse | Send status "HTTP/1.1   200 OK"
810 | WebResponse | Send header "Content-Type:   text/html; charset=utf-8"

**Comment by ecorrons** [comment]
Hola, mm no veo ningún error en ese log. probaste entrar desde modo development como te dije arriba? y al wkhtmltopdf  lo instalaron como dice acá en el archivo INSTALL? https://github.com/Desarrollo-CeSPI/kimkelen/blob/master/INSTALL

**Comment by ggallino** [comment]
Solucionado... Volvimos a instalar siguiendo el instructivo que me especificaste...
Muchas gracias!!

**Comment by ecorrons** [comment]
Me alegro @ggallino !!
Saludos
