### ISSUE TITLE
Consulta modificación

### ISSUE THREAD

**Issue by belenrs** [Desarrollo-CeSPI/kimkelen#442]
Hola! tengo la siguiente consulta:
Para agregar categorías de asignaturas (por comisión, optativas, de la orientación), ¿es conveniente agregar un campo en 'subject_configuration' (tal como 'course_type'), o en 'career_subject' (tal como 'is_option' que indica que la materia es opcional) o en subject, agregar, type, desde otra tabla de tipos de materia?
Luego, el alumno tiene que estar vinculado con asistencia por día o por hora cátedra según el tipo de asignatura que sea, ¿qué se debería modificar para contemplar  asistencia por asignatura?
Muchas Gracias!

**Comment by ecorrons** [comment]
Creo que las mismas dudas están planteadas en este otro [hilo](https://github.com/Desarrollo-CeSPI/kimkelen/issues/452) :)

**Comment by belenrs** [comment]
Si, así es, aunque esta fue primera, las dudas fueron resueltas. Muchas gracias!!
