### ISSUE TITLE
 Parse error: syntax error, unexpected '<' in  

### ISSUE THREAD

**Issue by renzovelazquez** [Desarrollo-CeSPI/kimkelen#454]
Hola Tengo instalado el sistema la Escuela Agrotécnica Eldorado, Dependente de la Universisdad Nacional de Misiones. 
Al Actualizar  la ultma version En varios listados estan dando el siguiente errro: 

Parse error: syntax error, unexpected '<' in /var/www/kimkelen/cache/backend/dev/modules/autoDivision/templates/_list_td_stacked.php on line 2
Dese ya muchas Gracias por la respuesta.

**Comment by renzovelazquez** [comment]
Solucionado!!
El error estaba cuando corri el patch.sql de la version 2.20.2
alter table school_year_student modify health_info VARCHAR(50) NOT NULL DEFAULT 'No entregado'; 
Como linea anterior  da un error,  entonces no ejecuta la siguiente. 
alter table school_year_student add date_health_info DATE default NULL;
Lo ejecute separadamente, esta agrega el campo add date_health_info y soluciona el error. Gracias.!!!

**Comment by ecorrons** [comment]
Me alegro @renzovelazquez que hayas podido solucionarlo
