### ISSUE TITLE
Consulta select provincia y ciudad

### ISSUE THREAD

**Issue by belenrs** [Desarrollo-CeSPI/kimkelen#457]
Hola Ma. Emilia, hola resto del equipo! disculpen la molestia, pero hace unos varios días que estamos viendo lo siguiente:
Descargamos e instalamos correctamente la versión 2.29.5  en una pc con ubuntu, corriendo xampp v1.7.7, con php 5.3.8.
Inicialmente, lo que necesitamos es setear por defecto, los select de provincia con el valor "La Pampa" y ciudad "Santa Rosa". Hemos visto en el flavor del colegio Pellegrini que redefinen el método getDefaultCityId y getDefaultStateId (con los valores de Buenos Aires y Ciudad Autónoma respectivamente, aunque creemos que van al revés) en PellegriniSchoolBehaviour.class.
Para el flavor demo, en DemoSchoolBehaviour no están redefinidos estos métodos, por lo que entendemos, el flavor tomará todo el comportamiento que está definido en /lib/school_behaviour/base pues allí están definidas las clases base de quien heredará cada flavor. En BaseSchoolBehaviour.class.php están definidos esos: métodos getDefaultCountryId() (que setea Argentina y eso anda ok), getDefaultStateId() (que setea Buenos Aires) y qetDefaultCityId() (que setea La Plata).
Si redefinimos en DemoSchoolBehaviour los métodos getDefaultCityId y getDefaultStateId con los valores que necesitamos, no ocurre nada. 
Si cambiamos para ejecutar el flavor del pellegrini, no ocurre nada.
Como está, ejecutando el flavor demo, debiera estar seleccionado Buenos Aires y La Plata pero tampoco ocurre nada.

Instalamos la versión  2.19.6 (pero que adentro te cambia a 2.19.5) que es la que tiene la demo que ofrecen, y con esa versión sí funcionan los select con los valores por defecto (Buenos Aires y La Plata), pero queríamos trabajar sobre la última versión que liberan puesto que entendemos es la que está más corregida. Pero, ¿puede ser que tenga un error en el comportamiento de los select de provincia y ciudad?
Espero sus respuestas porque la verdad me genera muchas dudas todo este comportamiento con las distintas versiones,
Desde ya, muchas gracias y saludos!

**Comment by nvidela** [comment]
Hola @belenrs, lo que podes hacer es definir una constante en la clase State que sea La Pampa con el valor correspondiente (5442)  y luego, como vos bien decis redefinir el metodo getDefaultSateId en la clase DemoSchoolBehaviour para que retorne esa constante. Tengan en cuenta de haber corrido todos los parches en la base de datos que se encuentran en la directorio < dir donde esta instalado kimkelen>/patch

Saludos

**Comment by nvidela** [comment]
Hola @belenrs  fijate haber definido bien la clase CivilStatusType (debe estar dentro del directorio /lib/reference), por ejemplo:

class CivilStatusType extends BaseCustomOptionsHolder
{
  const
    soltero   = 1,
    casado = 2;

  protected
    $_options = array(
        self::soltero      => 'Soltero',
        self::casado    => 'Casado'
      );

En el formulario PersonForm agregar las lineas: 

 $this->setWidget('civil_status', new sfWidgetFormSelect(array(
      'choices'  => BaseCustomOptionsHolder::getInstance('CivilStatusType')->getOptions()
    )));

    $this->setValidator('civil_status', new sfValidatorChoice(array(
        'choices' => BaseCustomOptionsHolder::getInstance('CivilStatusType')->getKeys())
    ));

volve a constuir el modelo y los formularios y limpia la cache:

php symfony propel:build-model
php symfony propel:build-forms
php symfony propel:build-filters
php symfony cc

Saludos,
Naimid

**Comment by belenrs** [comment]
Muchas gracias! si, efectivamente se solucionó volviendo a construir el modelo, los formularios y limpiando la cache. Lo demás que indicás es lo que estaba haciendo, pero faltaba eso. Ahora anduvo. Muchas gracias!!!
