### ISSUE TITLE
Problemas de instalacion  version 2.30.3

### ISSUE THREAD

**Issue by RonaldFritz** [Desarrollo-CeSPI/kimkelen#481]
Buenas tardes, estoy tratando de instalar el sistema en una escuela publica de comodoro rivadavia, en una pc para probarlo y luego usarlo. tiene windows 10 y wamp instalado con versión de php 7.2.4 ya probé también con la version 5.6.  el script para ver si tengo todos los requerimientos me da ok. Cree la base de datos modifique los archivos propel y database todo como dice el archivo readme. Al ejecutar los comandos php, con el de flavor demo me da una serie de warning, con el de propel:buil-all-load muchos errores como:

[PHP Error] Non-static method DOMDocument::load() should not be called statically, assuming $this from incompatible context [line 442 of C:\wamp64\www\kimkelen\lib\symfony\plugins\sfPropelPlugin\lib\vendor\propel-generator\classes\propel\phing\AbstractPropelDataModelTask.php]

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\wamp64\www\kimkelen\lib\symfony\command\sfCommandManager.class.php on line 111

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\wamp64\www\kimkelen\lib\symfony\util\sfToolkit.class.php on line 388

El resto de los comandos me dan errores similares. no se si sera la version del windows 10 64bit o la versión de php. Agradeciese mucho su ayuda. Saludos. Escuela Provincial N°711 "Federico Brandsen" Comodoro Rivadavia

**Comment by arielch** [comment]
> wamp instalado con versión de php 7.2.4 ya probé también con la version 5.6

Según el [INSTALL](https://github.com/Desarrollo-CeSPI/kimkelen/blob/master/INSTALL) la versión de PHP tiene que ser mayor o igual a 5.2.4 y menor que 5.4.

No obstante, puedes evitar este error

> [PHP Error] Non-static method DOMDocument::load() should not be called statically, assuming $this from incompatible context [line 442 of C:\wamp64\www\kimkelen\lib\symfony\plugins\sfPropelPlugin\lib\vendor\propel-generator\classes\propel\phing\AbstractPropelDataModelTask.php]

instanciando DOMDocument y luego invocas load() en la instancia, porque no es un método estático; abre el archivo 

`C:\wamp64\www\kimkelen\lib\symfony\plugins\sfPropelPlugin\lib\vendor\propel-generator\classes\propel\phing\AbstractPropelDataModelTask.php`

y cambia la [línea 442](https://github.com/Desarrollo-CeSPI/kimkelen/blob/4dbcafa4842d6ebbeac204095d367091b0fa42b8/lib/symfony/plugins/sfPropelPlugin/lib/vendor/propel-generator/classes/propel/phing/AbstractPropelDataModelTask.php#L442), reemplaza

```php
$xsl->importStyleSheet(DomDocument::load($this->xslFile->getAbsolutePath()));
```
por

```php
$xslDoc = new DomDocument('1.0', 'UTF-8');
$xslDoc->load($this->xslFile->getAbsolutePath());
$xsl->importStyleSheet($xslDoc);
```

En Fedora, con PHP 7.1.16, hay otro error en [lib/model/CareerSubjectSchoolYearPeer.php](https://github.com/Desarrollo-CeSPI/kimkelen/blob/4dbcafa4842d6ebbeac204095d367091b0fa42b8/lib/model/CareerSubjectSchoolYearPeer.php#L25); si encuentras el error con tu versión de PHP, cambia

```php
  static public function getAvailableChoicesCriteria($career_subject_school_year, $exclude_related = true, $exclude_related = true)
  {
    return SchoolBehaviourFactory::getInstance()->getAvailableChoicesForCareerSubjectSchoolYearCriteria($career_subject_school_year, $exclude_related, $exclude_related);
  }
```

por

```php
  static public function getAvailableChoicesCriteria($career_subject_school_year, $exclude_related = true, $exclude_repetead = true)
  {
    return SchoolBehaviourFactory::getInstance()->getAvailableChoicesForCareerSubjectSchoolYearCriteria($career_subject_school_year, $exclude_related, $exclude_repetead);
  }
```

**Comment by RonaldFritz** [comment]
Muchas gracias por contestar, voy a probar. Igual solucione instalando con la version 5.3.8 lo cual anduvo pero no logro que aparezca el menu.

**Comment by sgpare** [comment]
Hola, ya hace más de medio año que intento instalar esta plataforma en mi escuela, pero no logro intalar correctamente versiones de php requeridas en ubuntu 16.04. Esto parece ser una solución para php 7 que se instala sin problemas. Quisiera saber si es así para concluir definitivamente la instalación. Gracias

**Comment by ncuesta** [comment]
Hola @sgpare, gracias por tu interés. Como se indica en el archivo [INSTALL](https://github.com/Desarrollo-CeSPI/kimkelen/blob/master/INSTALL#L6), la versión de PHP requerida es **>= 5.2.4 y < 5.4**.

Tenés la alternativa de ejecutar, por ejemplo, con Docker una versión de PHP anterior a la 7 en una versión reciente de Ubuntu utilizando herramientas como [phpdock](https://github.com/lucasdc6/phpdock).

¡Saludos!

**Comment by sgpare** [comment]
No encuentro solución para este problema. usuario: root y password: root al correr symfony propel:build-all-load --no-confirmation

 Some problems occurred when executing the task:                                                                               
    build-propel.xml:275:1:  [wrapped: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)]  
    If the exception message is not clear enough, read the output of the task for more information

**Comment by ncuesta** [comment]
@sgpare, la configuración de acceso a la base de datos se realiza en los archivos `config/database.yml` y `config/propel.ini`, tal [como se describe en el archivo `INSTALL`](https://github.com/Desarrollo-CeSPI/kimkelen/blob/master/INSTALL#L20).

Te pido, además, que cualquier inconveniente que tengas los reportes en un nuevo Issue, ya que lo que venís reportando no está relacionado al problema que este ticket intentó solucionar.
