### ISSUE TITLE
Equivalencias

### ISSUE THREAD

**Issue by smarevalo** [Desarrollo-CeSPI/kimkelen#486]
Hola, estoy utilizando la version 2.20.6, y tengo un alumno que viene de otra escuela, ingresa en segundo y tiene materias por equivalencias de primer año y le quedan otras que tiene que rendir como previas, como se hace en este caso, ya que cuando trato de ingresar en la opcion de equivalencias me figura el siguiente error:

Error
La página que estás buscando no existe.
¿Escribió la dirección URL a mano?
    Es posible que haya escrito la dirección (URL) incorrectamente. Compruebe para asegurarse que tienes la ortografía correcta, capitalización, etc 

Me pasa lo mismo en el demo que esta en http://demo.kimkelen.cespi.unlp.edu.ar/student/205/equivalence

Muchas gracias
Saludos

**Comment by nvidela** [comment]
Hola @smarevalo el módulo de equivalencias no está implementado en Kimkelen.

Saludos
