### ISSUE TITLE
Permisos

### ISSUE THREAD

**Issue by smarevalo** [Desarrollo-CeSPI/kimkelen#494]
Hola, estoy utilizando la version 2.20.6, y necesito darle permisos a los jefes de preceptores para que puedan ver el listado de sanciones de los alumnos, pero les doy los permisos sin embargo no me aparecen en el menu y al querer acceder directamente a /kimkelen/web/backend_dev.php/sanction me dice " Usted no posee permisos para acceder a esta sección". Debo realizar alguna otra acciòn para que haga efecto este permiso sobre el grupo de usuarios?

Muchas gracias

**Comment by nvidela** [comment]
Hola @smarevalo fijate que en el directorio <kimkelen>/patch/2.16.4 se encuentra un parche para aplicarle a la base de datos. Eso inserta el permiso que estás necesitando para acceder a esa operación.

Saludos

**Comment by smarevalo** [comment]
Perfecto, era lo que necesitaba, muchas gracias
