### ISSUE TITLE
Analiticos datos extra

### ISSUE THREAD

**Issue by smarevalo** [Desarrollo-CeSPI/kimkelen#499]
Hola, queria saber como poder agregar unos input en el analitico para datos como nro de folio, etc. y que me aparezcan al momento de imprimir.

Muchas gracias

**Comment by nvidela** [comment]
Hola @smarevalo a partir de la versión 2.31.3 en el flavor lvm  está implementado esto que vos necesitás. Tenés que exender el formulario AnalyticForm y la vista analyticalSuccess. 

Saludos
