### ISSUE TITLE
Instalar en windows

### ISSUE THREAD

**Issue by MarianoNz** [Desarrollo-CeSPI/kimkelen#50]
Me gustaría pedirles mas información de como instalar kimkelen en windows y de que se necesita tener instalado antes. Vi en su pagina que pide apache, php5 y mysql yo instale xampp que te instala todo eso y de ahí me perdí..
En donde corro los comandos 
php symfony kimkelen:flavor <COMPORTAMIENTO>
php symfony propel:build-all-load 
php symfony plugin:publish
php symfony project:permissions
? necesito instalar algo para correrlos?

Se necesita capistrano si o si para instalar?
Son cosas que nunca he usado asi que cualquier ayuda sera bienvenida.
Gracias
Mariano Núñez

**Comment by dskontrol** [comment]
Hola.. Me podrian ayudar.. Ejecute el comando   php symfony kimkelen:flavor  y me salio esto.. Me podrian dar una mano??.. Muchas gracias.
The execution of task "kimkelen:flavor" failed.
  - Not enough arguments.


symfony kimkelen:flavor  flavor

**Comment by ncuesta** [comment]
@dskontrol te está faltando especificar el *flavor*:

El error lo marca al final:

`symfony kimkelen:flavor FLAVOR`

Donde *`FLAVOR`* es el nombre de un flavor de los que tengas en el directorio de flavors.

**Comment by dskontrol** [comment]
buenas.. muchas gracias. avanze un poco mas.. ahora me salio esto  al ejecutar el siguiente comando
c:\xampp\php\php symfony plugin:publish
>> plugin    Configuring plugin - sfPropelPlugin
>> plugin    Configuring plugin - sfProtoculousPlugin
>> plugin    Configuring plugin - dcFormExtraPlugin
>> plugin    Configuring plugin - dcReloadedFormExtraPlugin

Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\kimkelen-2.18.2\lib\sym
fony\task\sfFilesystem.class.php on line 224
>> plugin    Configuring plugin - dcStatefulSecurityPlugin
>> plugin    Configuring plugin - ncPropelChangeLogBehaviorPlugin

Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\kimkelen-2.18.2\lib\sym
fony\task\sfFilesystem.class.php on line 224
>> plugin    Configuring plugin - pmJSCookMenuPlugin

Warning: symlink(): Cannot create symlink, error code(183) in C:\xampp\htdocs\kimkelen-2.18.2\lib\sym

hace falta instalar capistrano? una vez finalizado con que direccion ejecuto kimkelen? muchas gracias desde ya.

**Comment by caargonzalez** [comment]
Buenos días...estoy tratando de instalar kimkelen en windows 7 y me arroja el siguiente error: warning symlink() Cannot create symlink, error code (1314) in sfFfilesystem.class.php on line 224

**Comment by ncuesta** [comment]
@caargonzalez Eso es un warning, no es un error. La instalación luego de eso debería continuar correctamente.

**Comment by caargonzalez** [comment]
En realidad si instala pero al momento de ejecutar el interface no muestra correctamente...alguna idea?

**Comment by ncuesta** [comment]
Para cada uno de los warnings esos que aparecieron, deberías copiar la carpeta `web` del plugin asociado en el directorio `web` de la raíz del proyecto, utilizando como nombre el del plugin.

En [este comentario](https://github.com/Desarrollo-CeSPI/kimkelen/issues/50#issuecomment-26447620) Juan Pablo lo explica.

**Comment by caargonzalez** [comment]
Revise lo de Juan Pablo y la unica carpeta q no aparece es ../plugins/sfTCPDFPlugin/web pero no se donde sacarla

**Comment by caargonzalez** [comment]
Porque el DEMO de la pagina oficial CeSPI - UNLP no funciona?

**Comment by ncuesta** [comment]
Lo que tenés que mirar es que en tu directorio `web/` de la raíz del proyecto contenga los directorios que mencionamos en el comentario que linkeé antes y, por las dudas, verificar que no estén vacíos (deberían tener subdirectorios imágenes, css y/o javascripts. Si están vacíos, borralos y copialos del directorio del plugin correspondiente.

**Comment by caargonzalez** [comment]
Eso precisamente hice y ya copie todos los plugins q faltaban..el único que no encuentro es sfTCPDFPlugin

**Comment by ncuesta** [comment]
@caargonzalez Pero se solucionó tu problema?

**Comment by caargonzalez** [comment]
No, aún no...puedo loguearme pero el interface no se aprecia adecuadamente

**Comment by ncuesta** [comment]
Podés adjuntar una captura de pantalla donde se vea la consola JS de tu navegador? Para ver qué assets están faltando.

**Comment by caargonzalez** [comment]
SyntaxError: missing ; before statement jquery.js:1:10
SyntaxError: missing ; before statement jquery-ui.js:1:13
ReferenceError: jQuery is not defined jquery.cookie.js:56:0
ReferenceError: jQuery is not defined no-conflict.js:1:0
ReferenceError: jQuery is not defined jquery.notification.js:1:0
ReferenceError: jQuery is not defined ui.datepicker-es.js:3:0

**Comment by ncuesta** [comment]
Qué navegador usás?

**Comment by caargonzalez** [comment]
firefox 37.0.2

**Comment by ncuesta** [comment]
Por algún motivo no está cargando bien el archivo de jquery. Podés corroborar que el contenido del mismo (el que intenta cargar el navegador) se vea bien?

**Comment by caargonzalez** [comment]
Volvi a descargar kimkelen y copie los jquery a la carpeta correspondiente y ahora salen estos errores:
GET 
http://localhost/kimkelen-2.18.3/web/ [HTTP/1.1 200 OK 4680ms]
GET 
http://localhost/kimkelen-2.18.3/web/sfProtoculousPlugin/js/prototype.js [HTTP/1.1 404 Not Found 600ms]
GET 
http://localhost/kimkelen-2.18.3/web/pmJSCookMenuPlugin/js/JSCookMenu.js [HTTP/1.1 404 Not Found 140ms]
GET 
http://localhost/kimkelen-2.18.3/web/pmJSCookMenuPlugin/js/ThemePanel/theme.js [HTTP/1.1 404 Not Found 200ms]
GET 
http://localhost/kimkelen-2.18.3/web/css/main.css [HTTP/1.0 500 Internal Server Error 470ms]
GET 
http://localhost/kimkelen-2.18.3/web/css/smoothness/jquery-ui-1.7.2.custom.css [HTTP/1.1 404 Not Found 630ms]
GET 
http://localhost/kimkelen-2.18.3/web/pmJSCookMenuPlugin/css/ThemePanel/theme.css [HTTP/1.1 404 Not Found 140ms]
GET 
http://localhost/kimkelen-2.18.3/web/css/login-backend.css [HTTP/1.0 500 Internal Server Error 650ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/jquery.js [HTTP/1.1 304 Not Modified 150ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/jquery-ui.js [HTTP/1.1 304 Not Modified 150ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/jquery.cookie.js [HTTP/1.1 304 Not Modified 230ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/no-conflict.js [HTTP/1.1 304 Not Modified 150ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/main.js [HTTP/1.1 304 Not Modified 170ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/jquery.notification.js [HTTP/1.1 304 Not Modified 290ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/i18n/ui.datepicker-es.js [HTTP/1.1 304 Not Modified 190ms]
GET 
http://localhost/kimkelen-2.18.3/web/js/jquery-1.6.2.min.js [HTTP/1.1 304 Not Modified 90ms]
SyntaxError: missing ; before statement jquery.js:1:10
SyntaxError: missing ; before statement jquery-ui.js:1:13
ReferenceError: jQuery is not defined jquery.cookie.js:56:0
ReferenceError: jQuery is not defined no-conflict.js:1:0
ReferenceError: jQuery is not defined jquery.notification.js:1:0
ReferenceError: jQuery is not defined ui.datepicker-es.js:3:0
GET 
http://localhost/kimkelen-2.18.3/web/pmJSCookMenuPlugin/js/JSCookMenu.js [HTTP/1.1 404 Not Found 10ms]
GET 
http://localhost/kimkelen-2.18.3/web/pmJSCookMenuPlugin/js/ThemePanel/theme.js [HTTP/1.1 404 Not Found 20ms]
GET 
http://localhost/kimkelen-2.18.3/web/css/main.css [HTTP/1.0 500 Internal Server Error 270ms]
GET 
http://localhost/kimkelen-2.18.3/web/css/smoothness/jquery-ui-1.7.2.custom.css [HTTP/1.1 404 Not Found 310ms]
GET 
http://localhost/kimkelen-2.18.3/web/pmJSCookMenuPlugin/css/ThemePanel/theme.css [HTTP/1.1 404 Not Found 0ms]
GET 
http://localhost/kimkelen-2.18.3/web/css/login-backend.css [HTTP/1.0 500 Internal Server Error 330ms]

**Comment by ncuesta** [comment]
@caargonzalez Los archivos evidentemente no están disponibles en el web/*, te recomendaría que revises eso.

**Comment by Chinuxs** [comment]
Malisimo!
