### ISSUE TITLE
Nota último trimestre

### ISSUE THREAD

**Issue by smarevalo** [Desarrollo-CeSPI/kimkelen#533]
Hola, queria consultar para saber como configurar para que si un alumno, aprueba los trimestres 1 y 2 con buenas notas y no aprueba el trimestre 3, vaya directamente a rendir en diciembre por mas que el promedio supere la nota minima.

Ejemplo:
1t               2t               3t            Promedio
6                7                5                  6             APRUEBA
6                8                4                  6             APRUEBA
8                7                3                  6             NO APRUEBA
2                8                8                  6             APRUEBA

Muchas gracias

**Comment by nvidela** [comment]
Hola @smarevalo , primero deberías configurar la carrera para que en este caso la nota mínima de aprobación sea 6. Esto se hace desde Académica >> años lectivos >> ver carreras >> configuración. Luego vas a tener que extender el método isApproved(CourseSubjectStudent $course_subject_student, $average, PropelPDO $con = null) de la clase BaseEvaluatorBehaviour, en la clase DemoEvaluatorBehaviour y chequear la condición de aprobado .

Debería ser algo así:

class DemoEvaluatorBehaviour extends BaseEvaluatorBehaviour
{
    public function isApproved(CourseSubjectStudent $course_subject_student, $average, PropelPDO $con = null)
    {
            $minimum_mark = $course_subject_student->getCourseSubject($con)->getCareerSubjectSchoolYear($con)->getConfiguration($con)->getCourseMinimunMark();
                
            return $average >= $minimum_mark
      && $course_subject_student->getMarkFor($course_subject_student->countCourseSubjectStudentMarks(null, false, $con), $con)->getMark() >= $this->getPosponedNote();

    }
}

Saludos.

**Comment by smarevalo** [comment]
Perfecto, muchas gracias!!
