### ISSUE TITLE
Carga de calificación

### ISSUE THREAD

**Issue by smarevalo** [Desarrollo-CeSPI/kimkelen#560]
Hola, hice la actualización a la versión 2.32, cuando cargo la califiación a un alumno solo me permite números enteros, en la versión anterior si podia hacerlo, a donde debo modificar para que me acepte notas con punto o coma (6.50).
El link al que accedo es /course_student_mark/update

Saludoss

**Comment by RonaldFritz** [comment]
buenas tardes, pudiste instalarlo?

**Comment by ecorrons** [comment]
Hola @smarevalo, fijate que se permita tipo de dato float en el schema (course-schema.yml) y también chequeá los validadores en las clase Form que dibuja la planilla de notas (debe ser CourseSubjectMarksForm.class.php)... que no vaya a haber sobre el campo mark alguno que valide solo números enteros (sfValidatorInteger).
Con eso debería bastar.

Saludos!

**Comment by smarevalo** [comment]
Hola, si lo habia resuelto, habia que cambiar sfValidatorInteger por sfValidatorNumber
